using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    private static readonly TimeSpan RespawnCooldown = TimeSpan.FromSeconds(350);

    [Dependency] private readonly IGameTiming _timing = default!;

    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? RespawnPressed;
    public event Action? GhostRolesPressed;
    private GhostComponent? _ghost;
    private int _prevNumberRoles;

    public GhostGui()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        RespawnButton.OnPressed += _ => RespawnPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleClass.Negative);
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleClass.Negative);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    public void Update(int? roles, GhostComponent? ghost)
    {
        _ghost = ghost;
        Update(roles, ghost?.CanReturnToBody);
        UpdateRespawnButton();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateRespawnButton();
    }

    private void UpdateRespawnButton()
    {
        if (_ghost == null)
        {
            RespawnButton.Disabled = true;
            RespawnButton.Text = Loc.GetString("ghost-gui-respawn-button");
            return;
        }

        var remaining = _ghost.TimeOfDeath + RespawnCooldown - _timing.RealTime;
        RespawnButton.Disabled = remaining > TimeSpan.Zero;
        RespawnButton.Text = remaining > TimeSpan.Zero
            ? Loc.GetString("ghost-gui-respawn-button-cooldown", ("seconds", Math.Ceiling(remaining.TotalSeconds)))
            : Loc.GetString("ghost-gui-respawn-button");
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
