// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using Content.Client.MainMenu.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.Photocopier;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.DeadSpace.Photocopier.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotocopierWindow : FancyWindow
{
    private static readonly Color ConsoleBackground = Color.FromHex("#070300F8");
    private static readonly Color ConsoleBackgroundSoft = Color.FromHex("#120700F0");
    private static readonly Color ConsoleBorder = Color.FromHex("#A85E1290");
    private static readonly Color ConsoleBorderSoft = Color.FromHex("#A85E1248");
    private static readonly Color ConsoleText = Color.FromHex("#FFB11A");

    private IPrototypeManager _protoManager;

    public event Action<PaperworkFormPrototype>? FormButtonPressed;
    public event Action<int, PhotocopierMode>? PrintButtonPressed;
    public event Action? CopyModeButtonPressed;
    public event Action? PrintModeButtonPressed;

    private readonly List<string> _categoryStrings = new();

    private string? _category;
    private PhotocopierMode _mode;

    private PhotocopierType _type;
    private bool _wasEmagged;

    private int _tonerLeft;
    private int _maxTonerAmount;

    public PhotocopierWindow(IPrototypeManager protoManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _protoManager = protoManager;

        Amount.SetButtons(new List<int> { -2, -1 }, new List<int> { 1, 2 });
        Amount.IsValid = n => n > 0 && n < 7;

        PrintButton.OnPressed += _ => PrintButtonPressed?.Invoke(Amount.Value, _mode);
        PrintButton.OnPressed += _ => PrintButton.Disabled = true;
        CopyModeButton.OnPressed += _ => CopyModeButtonPressed?.Invoke();
        PrintModeButton.OnPressed += _ => PrintModeButtonPressed?.Invoke();

        SearchBar.OnTextChanged += OnSearchBarTextChanged;

        ApplyEclipseStyle();
    }

    private void ApplyEclipseStyle()
    {
        SearchBar.MinHeight = 24f;
        SearchBar.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
        };

        TonerAmount.BackgroundStyleBoxOverride = Rounded(ConsoleBackgroundSoft, ConsoleBorderSoft, 3f);
        TonerAmount.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#A85E12CC"),
        };

        StyleActionButton(CopyModeButton);
        StyleActionButton(PrintModeButton);
        StyleActionButton(PrintButton);
    }

    public void UpdateState(PhotocopierUiState state)
    {
        _mode = state.Mode;
        _type = state.Type;
        _wasEmagged = state.WasEmagged;
        _tonerLeft = state.TonerLeft;
        _maxTonerAmount = state.MaxTonerAmount;

        PrintButton.Disabled = !state.CanPrint;
        TonerCounter.Text = _tonerLeft + "/" + _maxTonerAmount;

        TonerAmount.MaxValue = _maxTonerAmount;
        TonerAmount.Value = _tonerLeft;

        if (state.Mode == PhotocopierMode.Copy)
        {
            CopyModeButton.Pressed = true;
            PrintModeButton.Pressed = false;
            if (!state.IsPaperInserted)
                PrintButton.Disabled = true;
        }
        if (state.Mode == PhotocopierMode.Print)
        {
            CopyModeButton.Pressed = false;
            PrintModeButton.Pressed = true;
            if (state.ChosenForm == null)
                PrintButton.Disabled = true;
        }

        PopulateCategories();
        PopulateForms();
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        PopulateForms();
    }

    public IEnumerable<PaperworkFormPrototype> PaperworkFormPrototypes => _protoManager.EnumeratePrototypes<PaperworkFormPrototype>();

    public void PopulateForms()
    {
        PaperworkForms.RemoveAllChildren();
        var forms = PaperworkFormPrototypes.ToList();
        forms.Sort((x, y) =>
            string.Compare(x.Name, y.Name, StringComparison.CurrentCultureIgnoreCase));

        var search = SearchBar.Text.Trim().ToLowerInvariant();
        foreach (var prototype in forms)
        {
            if (search.Length == 0 && _category == null ||
                search.Length != 0 && Loc.GetString(prototype.Name).ToLowerInvariant().Contains(search) ||
                search.Length == 0 && _category != null && prototype.Category.Equals(_category))
            {
                if (_categoryStrings.Contains(prototype.Category))
                {
                    var button = new Button();
                    button.Text = Loc.GetString(prototype.Name);
                    button.ToggleMode = false;
                    StyleConsoleButton(button);
                    button.OnPressed += _ => FormButtonPressed?.Invoke(prototype);
                    PaperworkForms.AddChild(button);
                }
            }
        }
    }

    public void PopulateCategories()
    {
        _categoryStrings.Clear();
        PaperworkCategories.DisposeAllChildren();

        // Please do not read code below, that's shitcode that I will fix someday
        foreach (var prototype in PaperworkFormPrototypes)
        {
            if (!_categoryStrings.Contains(prototype.Category))
            {
                if (_wasEmagged)
                {
                    if (prototype.Category == "operator")
                    {
                        continue;
                    }
                    _categoryStrings.Add(prototype.Category);
                }
                else if (_type == PhotocopierType.Centcomm)
                {
                    if (prototype.Category == "nukeops" || prototype.Category == "syndicate")
                    {
                        continue;
                    }
                    _categoryStrings.Add(prototype.Category);
                }
                else if (_type == PhotocopierType.Syndicate)
                {
                    if (prototype.Category == "operator" || prototype.Category == "nukeops")
                    {
                        continue;
                    }
                    _categoryStrings.Add(prototype.Category);
                }
                else if (_type == PhotocopierType.Nukeops)
                {
                    if (prototype.Category == "operator" || prototype.Category == "syndicate")
                    {
                        continue;
                    }
                    _categoryStrings.Add(prototype.Category);
                }
                else if (_type == PhotocopierType.Command)
                {
                    if (prototype.Category == "operator" || prototype.Category == "nukeops" || prototype.Category == "syndicate")
                    {
                        continue;
                    }
                    _categoryStrings.Add(prototype.Category);
                }
                else if (_type == PhotocopierType.Default)
                {
                    if (prototype.Category == "operator" || prototype.Category == "nukeops" || prototype.Category == "syndicate" || prototype.Category == "centcomm")
                    {
                        continue;
                    }
                    _categoryStrings.Add(prototype.Category);
                }
            }
        }

        _categoryStrings.Sort();

        foreach (var str in _categoryStrings)
        {
            var button = new Button();
            button.Text = Loc.GetString("photocopier-ui-categorie-title-" + str);
            button.ToggleMode = false;
            StyleConsoleButton(button);
            button.OnPressed += args => OnCategorySelected(args, str);
            PaperworkCategories.AddChild(button);
        }
    }

    public void OnCategorySelected(BaseButton.ButtonEventArgs args, string str)
    {
        _category = str;
        PopulateForms();
    }

    private static void StyleActionButton(Button button)
    {
        button.StyleBoxOverride = Rounded(ConsoleBackgroundSoft, ConsoleBorderSoft, 3f);
        button.ModulateSelfOverride = ConsoleText;
    }

    private static void StyleConsoleButton(Button button)
    {
        button.HorizontalExpand = true;
        button.MinHeight = 26f;
        button.Margin = new Thickness(0, 0, 0, 3);
        button.StyleBoxOverride = Rounded(ConsoleBackground, ConsoleBorderSoft, 3f);
        button.ModulateSelfOverride = ConsoleText;
    }

    private static EclipseStyleBoxRounded Rounded(Color background, Color border, float radius)
    {
        return new EclipseStyleBoxRounded
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = border.A > 0 ? new Thickness(1) : new Thickness(0),
            Radius = radius,
        };
    }
}
