using Content.Client.CrewManifest.UI;
using Content.Client.MainMenu.UI;
using Content.Shared.CrewManifest;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.CrewManifest;

[GenerateTypedNameReferences]
public sealed partial class CrewManifestUi : DefaultWindow
{
    public CrewManifestUi()
    {
        RobustXamlLoader.Load(this);

        ContentsContainer.Margin = new Thickness(0);
        WindowHeader.PanelOverride = EclipsePanel("#07111AEF", "#A85E12CC", 8f, 8f, 3f);
        TitleLabel.StyleIdentifier = MainMenuControl.StyleIdentifierHeaderGold;
        CloseButton.ModulateSelfOverride = Color.FromHex("#E6A11A");

        RootPanel.PanelOverride = EclipsePanel("#02070CF4", "#A85E1270", 8f, 0f, 0f);
        StationNameContainer.PanelOverride = EclipsePanel("#251600D8", "#A85E1270", 5f, 8f, 4f);
        StationName.StyleIdentifier = MainMenuControl.StyleIdentifierHeaderGold;
    }

    public void Populate(string name, CrewManifestEntries? entries)
    {
        CrewManifestListing.RemoveAllChildren();

        StationNameContainer.Visible = entries != null;
        StationName.Text = name;

        if (entries == null)
            return;

        CrewManifestListing.AddCrewManifestEntries(entries);
    }

    private static EclipseStyleBoxRounded EclipsePanel(
        string background,
        string border,
        float radius,
        float horizontalPadding,
        float verticalPadding)
    {
        var style = new EclipseStyleBoxRounded
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            Radius = radius,
        };

        style.SetContentMarginOverride(StyleBox.Margin.Horizontal, horizontalPadding);
        style.SetContentMarginOverride(StyleBox.Margin.Vertical, verticalPadding);
        return style;
    }
}
