using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using System;
using System.Globalization;
using System.Numerics;
using Content.Client.MainMenu.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IUriOpener _uriOpener = default!;

        private static readonly Uri WebsiteUri = new("https://eclipse-station.online");

        private const float SidebarWidth = 280f;
        private const float RightWidth = 390f;
        private const float EdgeGap = 40f;
        private const float NarrowEdgeGap = 12f;
        private const float NarrowBreakpoint = 900f;
        private const float CenterLeft = 360f;
        private const float TopGap = 24f;
        private const float AccountHeight = 92f;
        private const float NewsWidth = 350f;
        private const float NewsHeight = 350f;
        private const float NewsBottomGap = 57f;
        private const float ServerActionsHeight = 70f;
        private const float BottomActionsHeight = 75f;
        private const float RightPanelTop = 115f;
        private const float BottomGap = 16f;
        private const float RightPanelBottomGap = BottomGap + BottomActionsHeight + 16f;
        private const float LaunchStatusWidth = 158f;
        private const float LaunchStatusAnimationSpeed = 5f;
        private const float AccountWidthWithLaunch = 775f;
        private readonly EclipseNewsEntry[] _news;
        private readonly StoreItem[] _storeItems;
        private EclipseNewsAdminWindow? _newsWindow;
        private LobbySection _section = LobbySection.Play;
        private bool _launchStatusTargetVisible = true;
        private float _launchStatusVisibility = 1f;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(this, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            SiteButton.OnPressed += _ => _uriOpener.OpenUri(WebsiteUri);
            PlaySectionButton.OnPressed += _ => ShowSection(LobbySection.Play);
            StoreSectionButton.OnPressed += _ => ShowSection(LobbySection.Store);
            AccountSectionButton.OnPressed += _ => ShowSection(LobbySection.Account);
            SettingsSectionButton.OnPressed += _ => ShowSection(LobbySection.Settings);
            SectionOptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            NewsAdminButton.OnPressed += _ => OpenNewsAdminWindow();

            _news =
            [
                new EclipseNewsEntry(
                    NewsDate1.Text ?? string.Empty,
                    NewsTitle1.Text ?? string.Empty,
                    NewsText1.Text ?? string.Empty,
                    "/Textures/Eclipse/MainMenu/news/news-tech.png"),
                new EclipseNewsEntry(
                    NewsDate2.Text ?? string.Empty,
                    NewsTitle2.Text ?? string.Empty,
                    NewsText2.Text ?? string.Empty,
                    "/Textures/Eclipse/MainMenu/news/news-update.png"),
                new EclipseNewsEntry(
                    NewsDate3.Text ?? string.Empty,
                    NewsTitle3.Text ?? string.Empty,
                    NewsText3.Text ?? string.Empty,
                    "/Textures/Eclipse/MainMenu/news/news-event.png"),
            ];

            _storeItems =
            [
                new StoreItem("\u041A\u041E\u0421\u0422\u042E\u041C ECLIPSE", "\u0423\u043D\u0438\u043A\u0430\u043B\u044C\u043D\u044B\u0439 \u043A\u043E\u0441\u0442\u044E\u043C", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u041E\u0434\u0435\u0436\u0434\u0430", 600, StoreCurrency.Shards, "/Textures/Clothing/OuterClothing/Hardsuits/deathsquad.rsi/icon.png", "\u0420\u0415\u041A\u041E\u041C\u0415\u041D\u0414\u0423\u0415\u041C\u041E\u0415"),
                new StoreItem("\u0424\u041E\u0420\u041C\u0410 \u041A\u0410\u041F\u0418\u0422\u0410\u041D\u0410", "\u041F\u0430\u0440\u0430\u0434\u043D\u044B\u0439 \u043E\u0431\u0440\u0430\u0437", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u041E\u0434\u0435\u0436\u0434\u0430", 1500, StoreCurrency.Merits, "/Textures/Clothing/Uniforms/Jumpsuit/captain.rsi/icon.png", "\u041D\u041E\u0412\u041E\u0415"),
                new StoreItem("\u0420\u0410\u041C\u041A\u0410 «\u041E\u0420\u0411\u0418\u0422\u0410»", "\u041F\u0440\u043E\u0444\u0438\u043B\u044C\u043D\u0430\u044F \u0440\u0430\u043C\u043A\u0430", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u041F\u0440\u043E\u0444\u0438\u043B\u044C", 750, StoreCurrency.Merits, "/Textures/Eclipse/MainMenu/news/news-update.png", "\u041D\u041E\u0412\u041E\u0415"),
                new StoreItem("\u0427\u0410\u0421\u042B \u0417\u0410\u0422\u041C\u0415\u041D\u0418\u042F", "\u041B\u043E\u0431\u0431\u0438-\u0443\u043A\u0440\u0430\u0448\u0435\u043D\u0438\u0435", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u041B\u043E\u0431\u0431\u0438", 250, StoreCurrency.Shards, "/Textures/Interface/VerbIcons/clock.svg.192dpi.png", "\u0420\u0415\u0414\u041A\u041E\u0415"),
                new StoreItem("\u0424\u041E\u0420\u041C\u0410 \u0421\u0411 «\u0417\u0410\u0422\u041C\u0415\u041D\u0418\u0415»", "\u0422\u0451\u043C\u043D\u044B\u0439 \u0432\u0430\u0440\u0438\u0430\u043D\u0442", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u041E\u0434\u0435\u0436\u0434\u0430", 900, StoreCurrency.Shards, "/Textures/Clothing/OuterClothing/WinterCoats/coathosarmored.rsi/icon.png", "\u041D\u041E\u0412\u041E\u0415"),
                new StoreItem("\u0424\u041E\u041D \u041F\u0420\u041E\u0424\u0418\u041B\u042F", "\u0422\u0443\u043C\u0430\u043D\u043D\u043E\u0441\u0442\u044C", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u041F\u0440\u043E\u0444\u0438\u043B\u044C", 350, StoreCurrency.Shards, "/Textures/Eclipse/MainMenu/news/news-event.png", null),
                new StoreItem("\u0414\u0415\u041A\u041E\u0420 «\u0424\u0418\u041A\u0423\u0421»", "\u0423\u044E\u0442 \u0434\u043B\u044F \u043B\u043E\u0431\u0431\u0438", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u041B\u043E\u0431\u0431\u0438", 350, StoreCurrency.Merits, "/Textures/_Orion/Structures/Furniture/potted_plants.rsi/plasma_plant.png", "\u041D\u041E\u0412\u041E\u0415"),
                new StoreItem("\u041D\u0410\u0411\u041E\u0420 \u041D\u041E\u0412\u0418\u0427\u041A\u0410", "\u0411\u0430\u0437\u043E\u0432\u044B\u0439 \u043D\u0430\u0431\u043E\u0440", "\u041D\u0430\u0431\u043E\u0440", 1200, StoreCurrency.Merits, "/Textures/Objects/Devices/pda.rsi/pda.png", null),
                new StoreItem("\u0420\u042E\u041A\u0417\u0410\u041A \u0418\u041D\u0416\u0415\u041D\u0415\u0420\u0410", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u0447\u0435\u0441\u043A\u0438\u0439 \u0441\u043A\u0438\u043D", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u0421\u043F\u0438\u043D\u0430", 450, StoreCurrency.Merits, "/Textures/_Orion/Clothing/Back/Backpacks/inteq_backpack.rsi/icon.png", "\u041D\u041E\u0412\u041E\u0415"),
                new StoreItem("ID-\u041A\u0410\u0420\u0422\u0410 3K", "\u041E\u0431\u043B\u0438\u043A \u043A\u0430\u0440\u0442\u044B", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u0410\u043A\u0441\u0435\u0441\u0441\u0443\u0430\u0440", 300, StoreCurrency.Merits, "/Textures/_Backmen/Objects/Misc/id_cards.rsi/idstationengineer.png", "\u041D\u041E\u0412\u041E\u0415"),
                new StoreItem("\u041F\u041E\u0421\u0422\u0415\u0420 \u00AB\u0417\u0410\u0422\u041C\u0415\u041D\u0418\u0415\u00BB", "\u0414\u0435\u043A\u043E\u0440 \u0434\u043B\u044F \u043B\u043E\u0431\u0431\u0438", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u041B\u043E\u0431\u0431\u0438", 300, StoreCurrency.Merits, "/Textures/_Orion/Structures/Wallmounts/Posters/inteq_posters.rsi/inteq_poster1.png", "\u041D\u041E\u0412\u041E\u0415"),
                new StoreItem("\u0414\u0420\u041E\u041D \u00AB\u0421\u041C\u041E\u0422\u0420\u0418\u0422\u0415\u041B\u042C\u00BB", "\u0421\u043F\u0443\u0442\u043D\u0438\u043A \u043F\u0440\u043E\u0444\u0438\u043B\u044F", "\u041A\u043E\u0441\u043C\u0435\u0442\u0438\u043A\u0430 • \u0421\u043F\u0443\u0442\u043D\u0438\u043A", 600, StoreCurrency.Merits, "/Textures/Eclipse/VA11_HallA/sparklestar.rsi/icon.png", "\u041D\u041E\u0412\u041E\u0415"),
            ];

            ApplyLobbyChatStyle();
            BuildStoreCatalog();
            SetLaunchStatusVisible(true);
            ShowSection(LobbySection.Play);
            ApplyEclipseLayout();
        }

        public void SetLaunchStatusVisible(bool visible)
        {
            _launchStatusTargetVisible = visible;

            if (visible)
            {
                LaunchStatus.Visible = true;
                LaunchStatus.ReservesSpace = true;
                LaunchDivider.Visible = true;
                LaunchDivider.ReservesSpace = true;
            }
        }

        public void SetAccountInfo(string accountName, string roleName, int level, int currentExperience, int nextLevelExperience, int merits, int shards)
        {
            AccountName.Text = accountName;
            AccountTitle.Text = roleName;
            AccountRole.Text = roleName;
            AccountLevel.Text = $"\u0423\u0440\u043E\u0432\u0435\u043D\u044C {level}";
            AccountExperience.Text = $"{FormatAmount(currentExperience)} / {FormatAmount(nextLevelExperience)} XP";
            AccountExperienceProgress.Value = nextLevelExperience <= 0
                ? 0f
                : Math.Clamp((float) currentExperience / nextLevelExperience, 0f, 1f);
            MeritBalance.Text = FormatAmount(merits);
            ShardBalance.Text = FormatAmount(shards);
            StoreMeritBalance.Text = FormatAmount(merits);
            StoreShardBalance.Text = FormatAmount(shards);
        }

        private static string FormatAmount(int value)
        {
            return value.ToString("N0", CultureInfo.InvariantCulture).Replace(",", " ");
        }

        public void SetNewsAdminControlsVisible(bool visible)
        {
            NewsAdminButton.Visible = visible;
        }

        private void OpenNewsAdminWindow()
        {
            if (_newsWindow is { Disposed: false })
            {
                _newsWindow.MoveToFront();
                return;
            }

            _newsWindow = new EclipseNewsAdminWindow(_news, ApplyNews);
            _newsWindow.OpenCentered();
        }

        private void ApplyNews()
        {
            ApplyNewsItem(_news[0], NewsDate1, NewsTitle1, NewsText1, NewsImage1);
            ApplyNewsItem(_news[1], NewsDate2, NewsTitle2, NewsText2, NewsImage2);
            ApplyNewsItem(_news[2], NewsDate3, NewsTitle3, NewsText3, NewsImage3);
        }

        private static void ApplyNewsItem(EclipseNewsEntry news, Label date, Label title, Label text, TextureRect image)
        {
            date.Text = news.Date;
            title.Text = news.Title;
            text.Text = news.Text;

            if (!string.IsNullOrWhiteSpace(news.TexturePath))
                image.TexturePath = news.TexturePath;
        }

        private void ApplyLobbyChatStyle()
        {
            Chat.ApplyEclipseChatStyle();
        }

        private void BuildStoreCatalog()
        {
            StoreCatalogGrid.RemoveAllChildren();

            for (var i = 1; i < _storeItems.Length; i++)
            {
                StoreCatalogGrid.AddChild(BuildStoreCard(_storeItems[i]));
            }

            if (_storeItems.Length > 0)
                ApplyStoreFeatured(_storeItems[0]);
        }

        private void ApplyStoreFeatured(StoreItem item)
        {
            StoreFeaturedImage.TexturePath = item.TexturePath;
            StoreFeaturedCurrencyIcon.TexturePath = GetStoreCurrencyIcon(item.Currency);
            StoreFeaturedName.Text = item.Name;
            StoreFeaturedDescription.Text = item.Description;
            StoreFeaturedPrice.Text = FormatAmount(item.Price);
        }

        private Control BuildStoreCard(StoreItem item)
        {
            var card = new PanelContainer
            {
                MinSize = new Vector2(204f, 244f),
                SetSize = new Vector2(204f, 244f),
                PanelOverride = StorePanel("#070300F4", item.Currency == StoreCurrency.Shards ? "#7B2BB990" : "#A85E1290", 1, 9, 9),
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 5,
                HorizontalExpand = true,
                VerticalExpand = true,
            };
            card.AddChild(root);

            var imageWrap = new PanelContainer
            {
                MinSize = new Vector2(0f, 92f),
                HorizontalExpand = true,
                PanelOverride = StorePanel("#070300D8", "#A85E1238", 1, 4, 4),
            };
            imageWrap.AddChild(new TextureRect
            {
                TexturePath = item.TexturePath,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalExpand = true,
                VerticalExpand = true,
            });
            root.AddChild(imageWrap);

            if (!string.IsNullOrWhiteSpace(item.Badge))
            {
                root.AddChild(new Label
                {
                    Text = item.Badge,
                    StyleIdentifier = MainMenuControl.StyleIdentifierGoldSmall,
                    ClipText = true,
                });
            }

            root.AddChild(new Label
            {
                Text = item.Name,
                StyleIdentifier = MainMenuControl.StyleIdentifierText,
                ClipText = true,
            });
            root.AddChild(new Label
            {
                Text = item.Kind,
                StyleIdentifier = MainMenuControl.StyleIdentifierTinySubtle,
                ClipText = true,
            });

            var priceRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 5,
                HorizontalExpand = true,
            };
            priceRow.AddChild(new TextureRect
            {
                TexturePath = GetStoreCurrencyIcon(item.Currency),
                SetSize = item.Currency == StoreCurrency.Shards
                    ? new Vector2(20f, 20f)
                    : new Vector2(18f, 18f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
            });
            priceRow.AddChild(new Label
            {
                Text = FormatAmount(item.Price),
                StyleIdentifier = MainMenuControl.StyleIdentifierGoldSmall,
                ClipText = true,
            });
            root.AddChild(priceRow);

            root.AddChild(new Control
            {
                VerticalExpand = true,
            });

            root.AddChild(new Button
            {
                Text = "\u041A\u0443\u043F\u0438\u0442\u044C",
                MinHeight = 30,
                HorizontalExpand = true,
                StyleIdentifier = item.Currency == StoreCurrency.Shards
                    ? MainMenuControl.StyleIdentifierPrimary
                    : MainMenuControl.StyleIdentifierSecondary,
            });

            return card;
        }

        private static string GetStoreCurrencyIcon(StoreCurrency currency)
        {
            return currency == StoreCurrency.Shards
                ? "/Textures/Eclipse/MainMenu/shard.png"
                : "/Textures/Eclipse/MainMenu/merit.png";
        }

        private static EclipseStyleBoxRounded StorePanel(string background, string border, int borderThickness, int horizontalMargin, int verticalMargin)
        {
            var style = new EclipseStyleBoxRounded
            {
                BackgroundColor = Color.FromHex(background),
                BorderColor = Color.FromHex(border),
                BorderThickness = new Thickness(borderThickness),
                Radius = 8f,
            };

            style.SetContentMarginOverride(StyleBox.Margin.Horizontal, horizontalMargin);
            style.SetContentMarginOverride(StyleBox.Margin.Vertical, verticalMargin);
            return style;
        }

        private void ShowSection(LobbySection section)
        {
            _section = section;
            var play = section == LobbySection.Play;

            TopStatusPanel.Visible = play;
            NewsPanel.Visible = play;
            ServerActions.Visible = true;
            RightSide.Visible = true;
            BottomActions.Visible = true;
            VoteContainer.Visible = play;
            SectionPanel.Visible = !play;
            StoreContent.Visible = section == LobbySection.Store;
            StoreHeaderBalances.Visible = section == LobbySection.Store;
            SectionBody.Visible = section != LobbySection.Store;
            SectionFiller.Visible = section != LobbySection.Store;

            PlaySectionButton.StyleIdentifier = play ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierNav;
            StoreSectionButton.StyleIdentifier = section == LobbySection.Store ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierNav;
            AccountSectionButton.StyleIdentifier = section == LobbySection.Account ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierNav;
            SettingsSectionButton.StyleIdentifier = section == LobbySection.Settings ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierNav;

            SectionOptionsButton.Visible = section == LobbySection.Settings;

            switch (section)
            {
                case LobbySection.Play:
                    break;
                case LobbySection.Store:
                    SectionIconTexture.TexturePath = "/Textures/Eclipse/MainMenu/icons/nav-store.png";
                    SectionTitle.Text = "\u041C\u0410\u0413\u0410\u0417\u0418\u041D";
                    SectionSubtitle.Text = "\u0412\u0438\u0442\u0440\u0438\u043D\u0430 \u043D\u0430\u0440\u044F\u0434\u043E\u0432 \u0438 \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u043E\u0432";
                    break;
                case LobbySection.Account:
                    SectionIconTexture.TexturePath = "/Textures/Eclipse/MainMenu/icons/nav-account.png";
                    SectionTitle.Text = "\u0410\u041A\u041A\u0410\u0423\u041D\u0422";
                    SectionSubtitle.Text = "\u041F\u0440\u043E\u0444\u0438\u043B\u044C, \u0430\u0432\u0430\u0442\u0430\u0440 \u0438 \u0434\u043E\u0441\u0442\u0438\u0436\u0435\u043D\u0438\u044F";
                    SectionBody.Text = "\u0417\u0434\u0435\u0441\u044C \u0431\u0443\u0434\u0435\u0442 \u043E\u0442\u0434\u0435\u043B\u044C\u043D\u044B\u0439 \u043F\u043E\u043B\u043D\u043E\u044D\u043A\u0440\u0430\u043D\u043D\u044B\u0439 \u043F\u0440\u043E\u0444\u0438\u043B\u044C \u0430\u043A\u043A\u0430\u0443\u043D\u0442\u0430. \u0410\u0432\u0430\u0442\u0430\u0440 \u043C\u043E\u0436\u043D\u043E \u0431\u0443\u0434\u0435\u0442 \u043C\u0435\u043D\u044F\u0442\u044C \u0432 \u044D\u0442\u043E\u043C \u0440\u0430\u0437\u0434\u0435\u043B\u0435.";
                    break;
                case LobbySection.Settings:
                    SectionIconTexture.TexturePath = "/Textures/Eclipse/MainMenu/icons/nav-settings.png";
                    SectionTitle.Text = "\u041D\u0410\u0421\u0422\u0420\u041E\u0419\u041A\u0418";
                    SectionSubtitle.Text = "\u0418\u0433\u0440\u0430 \u0438 \u0438\u043D\u0442\u0435\u0440\u0444\u0435\u0439\u0441";
                    SectionBody.Text = "\u0417\u0434\u0435\u0441\u044C \u0431\u0443\u0434\u0435\u0442 \u043E\u0442\u0434\u0435\u043B\u044C\u043D\u044B\u0439 \u043F\u043E\u043B\u043D\u043E\u044D\u043A\u0440\u0430\u043D\u043D\u044B\u0439 \u0440\u0430\u0437\u0434\u0435\u043B \u043D\u0430\u0441\u0442\u0440\u043E\u0435\u043A.";
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(section), section, null);
            }

            ApplyEclipseLayout();
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    ShowSection(_section);
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    SectionPanel.Visible = false;
                    TopStatusPanel.Visible = false;
                    NewsPanel.Visible = false;
                    ServerActions.Visible = true;
                    RightSide.Visible = true;
                    BottomActions.Visible = true;
                    VoteContainer.Visible = false;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }

            ApplyEclipseLayout();
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            UpdateLaunchStatusAnimation(args.DeltaSeconds);
            ApplyEclipseLayout();
        }

        private void UpdateLaunchStatusAnimation(float deltaSeconds)
        {
            var target = _launchStatusTargetVisible ? 1f : 0f;
            _launchStatusVisibility = Math.Clamp(
                _launchStatusVisibility + MathF.Sign(target - _launchStatusVisibility) * deltaSeconds * LaunchStatusAnimationSpeed,
                0f,
                1f);

            if (MathF.Abs(_launchStatusVisibility - target) < 0.001f)
                _launchStatusVisibility = target;

            LaunchStatus.Visible = true;
            LaunchStatus.ReservesSpace = true;
            LaunchDivider.Visible = true;
            LaunchDivider.ReservesSpace = true;
            LaunchStatus.SetWidth = LaunchStatusWidth;
            LaunchStatus.Modulate = Color.White.WithAlpha(_launchStatusVisibility);
            LaunchDivider.Modulate = Color.White.WithAlpha(_launchStatusVisibility);
        }

        private void ApplyEclipseLayout()
        {
            var width = MathF.Max(MainContainer.Width, 1f);
            var height = MathF.Max(MainContainer.Height, 1f);
            var rightGap = width < NarrowBreakpoint ? NarrowEdgeGap : EdgeGap;
            var rightWidth = Math.Clamp(width - rightGap - CenterLeft, 320f, RightWidth);
            var rightStart = width - rightGap - rightWidth;
            var availableCenterWidth = rightStart - CenterLeft - 42f;
            var accountWidth = Math.Clamp(availableCenterWidth, 640f, AccountWidthWithLaunch);
            var newsWidth = Math.Min(NewsWidth, Math.Max(availableCenterWidth, 320f));

            SetLeftStretch(LeftSide, 0f, SidebarWidth);
            SetTopLeft(TopStatusPanel, CenterLeft, TopGap, accountWidth, AccountHeight);
            SetBottomLeft(NewsPanel, CenterLeft, NewsBottomGap, newsWidth, NewsHeight);
            SetTopRight(ServerActions, rightGap, TopGap, rightWidth, ServerActionsHeight);
            SetRightStretch(RightSide, rightGap, RightPanelTop, rightWidth, RightPanelBottomGap);
            SetTopRight(ExpandPanel, rightGap, RightPanelTop, 44f, 44f);
            SetBottomRight(BottomActions, rightGap, BottomGap, rightWidth, BottomActionsHeight);
            SetTopLeft(VoteContainer, CenterLeft, TopGap + AccountHeight + 12f, Math.Clamp(accountWidth, 360f, 640f), 180f);
            var centerRightReserve = RightSide.Visible ? rightGap + rightWidth + 28f : rightGap;
            SetTopLeft(SectionPanel, SidebarWidth, 0f, MathF.Max(width - SidebarWidth - centerRightReserve, 1f), height);

            var setupLeft = SidebarWidth + 28f;
            var setupWidth = Math.Max(width - setupLeft - centerRightReserve, 480f);
            SetTopLeft(CharacterSetupState, setupLeft, TopGap, setupWidth, MathF.Max(height - TopGap - BottomGap, 640f));
        }

        private static void SetTopLeft(Control control, float left, float top, float width, float height)
        {
            LayoutContainer.SetAnchorLeft(control, 0f);
            LayoutContainer.SetAnchorTop(control, 0f);
            LayoutContainer.SetAnchorRight(control, 0f);
            LayoutContainer.SetAnchorBottom(control, 0f);
            LayoutContainer.SetMarginLeft(control, left);
            LayoutContainer.SetMarginTop(control, top);
            LayoutContainer.SetMarginRight(control, left + width);
            LayoutContainer.SetMarginBottom(control, top + height);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetTopRight(Control control, float right, float top, float width, float height)
        {
            LayoutContainer.SetAnchorLeft(control, 1f);
            LayoutContainer.SetAnchorTop(control, 0f);
            LayoutContainer.SetAnchorRight(control, 1f);
            LayoutContainer.SetAnchorBottom(control, 0f);
            LayoutContainer.SetMarginLeft(control, -(right + width));
            LayoutContainer.SetMarginTop(control, top);
            LayoutContainer.SetMarginRight(control, -right);
            LayoutContainer.SetMarginBottom(control, top + height);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetBottomLeft(Control control, float left, float bottom, float width, float height)
        {
            LayoutContainer.SetAnchorLeft(control, 0f);
            LayoutContainer.SetAnchorTop(control, 1f);
            LayoutContainer.SetAnchorRight(control, 0f);
            LayoutContainer.SetAnchorBottom(control, 1f);
            LayoutContainer.SetMarginLeft(control, left);
            LayoutContainer.SetMarginTop(control, -(bottom + height));
            LayoutContainer.SetMarginRight(control, left + width);
            LayoutContainer.SetMarginBottom(control, -bottom);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetBottomRight(Control control, float right, float bottom, float width, float height)
        {
            LayoutContainer.SetAnchorLeft(control, 1f);
            LayoutContainer.SetAnchorTop(control, 1f);
            LayoutContainer.SetAnchorRight(control, 1f);
            LayoutContainer.SetAnchorBottom(control, 1f);
            LayoutContainer.SetMarginLeft(control, -(right + width));
            LayoutContainer.SetMarginTop(control, -(bottom + height));
            LayoutContainer.SetMarginRight(control, -right);
            LayoutContainer.SetMarginBottom(control, -bottom);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetRightStretch(Control control, float right, float top, float width, float bottom)
        {
            LayoutContainer.SetAnchorLeft(control, 1f);
            LayoutContainer.SetAnchorTop(control, 0f);
            LayoutContainer.SetAnchorRight(control, 1f);
            LayoutContainer.SetAnchorBottom(control, 1f);
            LayoutContainer.SetMarginLeft(control, -(right + width));
            LayoutContainer.SetMarginTop(control, top);
            LayoutContainer.SetMarginRight(control, -right);
            LayoutContainer.SetMarginBottom(control, -bottom);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetLeftStretch(Control control, float left, float width)
        {
            LayoutContainer.SetAnchorLeft(control, 0f);
            LayoutContainer.SetAnchorTop(control, 0f);
            LayoutContainer.SetAnchorRight(control, 0f);
            LayoutContainer.SetAnchorBottom(control, 1f);
            LayoutContainer.SetMarginLeft(control, left);
            LayoutContainer.SetMarginTop(control, 0f);
            LayoutContainer.SetMarginRight(control, left + width);
            LayoutContainer.SetMarginBottom(control, 0f);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }

        private enum LobbySection : byte
        {
            Play,
            Store,
            Account,
            Settings,
        }

        private enum StoreCurrency : byte
        {
            Merits,
            Shards,
        }

        private sealed record StoreItem(
            string Name,
            string Description,
            string Kind,
            int Price,
            StoreCurrency Currency,
            string TexturePath,
            string? Badge);

        private sealed class EclipseNewsEntry
        {
            public EclipseNewsEntry(string date, string title, string text, string texturePath)
            {
                Date = date;
                Title = title;
                Text = text;
                TexturePath = texturePath;
            }

            public string Date { get; set; }
            public string Title { get; set; }
            public string Text { get; set; }
            public string TexturePath { get; set; }
        }

        private sealed class EclipseNewsAdminWindow : DefaultWindow
        {
            private readonly EclipseNewsEntry[] _entries;
            private readonly Action _onSaved;
            private readonly LineEdit[] _dateEdits = new LineEdit[3];
            private readonly LineEdit[] _titleEdits = new LineEdit[3];
            private readonly LineEdit[] _textEdits = new LineEdit[3];
            private readonly LineEdit[] _textureEdits = new LineEdit[3];

            public EclipseNewsAdminWindow(EclipseNewsEntry[] entries, Action onSaved)
            {
                _entries = entries;
                _onSaved = onSaved;

                Title = "Eclipse news";
                MinSize = new Vector2(620f, 500f);

                var root = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = 10,
                    Margin = new Thickness(12),
                    HorizontalExpand = true,
                    VerticalExpand = true,
                };

                for (var i = 0; i < entries.Length; i++)
                {
                    root.AddChild(BuildEditor(i));
                }

                var saveButton = new Button
                {
                    Text = "Save news",
                    MinHeight = 36,
                    HorizontalExpand = true,
                };
                saveButton.OnPressed += _ => SaveAndClose();
                root.AddChild(saveButton);

                Contents.AddChild(root);
            }

            private Control BuildEditor(int index)
            {
                var entry = _entries[index];
                var box = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = 4,
                    HorizontalExpand = true,
                };

                box.AddChild(new Label
                {
                    Text = $"News {index + 1}",
                    StyleIdentifier = MainMenuControl.StyleIdentifierGoldSmall,
                });

                _dateEdits[index] = AddLineEdit(box, "Date", entry.Date);
                _titleEdits[index] = AddLineEdit(box, "Title", entry.Title);
                _textEdits[index] = AddLineEdit(box, "Text", entry.Text);
                _textureEdits[index] = AddLineEdit(box, "Texture path", entry.TexturePath);

                return box;
            }

            private static LineEdit AddLineEdit(BoxContainer parent, string placeholder, string text)
            {
                var edit = new LineEdit
                {
                    PlaceHolder = placeholder,
                    Text = text,
                    HorizontalExpand = true,
                };
                parent.AddChild(edit);
                return edit;
            }

            private void SaveAndClose()
            {
                for (var i = 0; i < _entries.Length; i++)
                {
                    _entries[i].Date = _dateEdits[i].Text.Trim();
                    _entries[i].Title = _titleEdits[i].Text.Trim();
                    _entries[i].Text = _textEdits[i].Text.Trim();
                    _entries[i].TexturePath = _textureEdits[i].Text.Trim();
                }

                _onSaved();
                Close();
            }
        }
    }
}
