using Content.Client.Message;
using Content.Client.CrewManifest;
using Content.Client.GameTicking.Managers;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.UserInterface.Systems.Bwoink;
using Content.Client.Voting;
using Content.Client.Voting.UI;
using Content.Shared.Eclipse.Progression;
using System;
using System.Globalization;
using System.Numerics;
using Content.Client.MainMenu.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Timing;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;
        [Dependency] private readonly IUriOpener _uriOpener = default!;
        [Dependency] private readonly IVoteManager _voteManager = default!;

        private static readonly Uri WebsiteUri = new("https://eclipse-station.online");
        private static readonly Color NavNormalColor = Color.FromHex("#A6A6A6");
        private static readonly Color NavActiveColor = Color.FromHex("#E6A11A");
        private static readonly Color NavSubtitleActiveColor = Color.FromHex("#D8D8D8");

        private const float SidebarWidth = 280f;
        private const float RightWidth = 390f;
        private const float EdgeGap = 40f;
        private const float NarrowEdgeGap = 12f;
        private const float NarrowBreakpoint = 900f;
        private const float CenterLeft = 360f;
        private const float TopGap = 24f;
        private const float AccountHeight = 92f;
        private const float NewsWidth = 350f;
        private const float NewsHeight = 350f;
        private const float NewsBottomGap = 57f;
        private const float ServerActionsHeight = 70f;
        private const float BottomActionsHeight = 75f;
        private const float RightPanelTop = 115f;
        private const float BottomGap = 16f;
        private const float RightPanelBottomGap = BottomGap + BottomActionsHeight + 16f;
        private const float LaunchStatusWidth = 158f;
        private const float LaunchStatusAnimationSpeed = 5f;
        private const float AccountWidthWithLaunch = 775f;
        private readonly EclipseNewsEntry[] _news;
        private readonly StoreItem[] _storeItems;
        private readonly RoadmapEntry[] _roadmapEntries;
        private EclipseNewsAdminWindow? _newsWindow;
        private VoteCallMenu? _voteCallMenu;
        private LobbySection _section = LobbySection.Play;
        private bool _launchStatusTargetVisible = true;
        private float _launchStatusVisibility = 1f;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(this, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            SiteButton.OnPressed += _ => _uriOpener.OpenUri(WebsiteUri);
            PlaySectionButton.OnPressed += _ => ShowSection(LobbySection.Play);
            StoreSectionButton.OnPressed += _ => ShowSection(LobbySection.Store);
            AccountSectionButton.OnPressed += _ => ShowSection(LobbySection.Account);
            SettingsSectionButton.OnPressed += _ => ShowSection(LobbySection.Settings);
            RoadmapSectionButton.OnPressed += _ => ShowSection(LobbySection.Roadmap);
            SectionOptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            NewsAdminButton.OnPressed += _ => OpenNewsAdminWindow();
            LobbyTabButton.OnPressed += _ => SetRightTabActive(RightSideTab.Lobby);
            ManifestTabButton.OnPressed += _ => OpenCrewManifest();
            AdminsTabButton.OnPressed += _ =>
            {
                SetRightTabActive(RightSideTab.Admins);
                UserInterfaceManager.GetUIController<AHelpUIController>().Open();
            };
            VotesTabButton.OnPressed += _ => OpenVoteMenu();
            RegisterNavHover(PlaySectionButton, PlaySectionIcon, PlaySectionTitle, PlaySectionSubtitle, () => _section == LobbySection.Play);
            RegisterNavHover(StoreSectionButton, StoreSectionIcon, StoreSectionTitle, StoreSectionSubtitle, () => _section == LobbySection.Store);
            RegisterNavHover(AccountSectionButton, AccountSectionIcon, AccountSectionTitle, AccountSectionSubtitle, () => _section == LobbySection.Account);
            RegisterNavHover(SettingsSectionButton, SettingsSectionIcon, SettingsSectionTitle, SettingsSectionSubtitle, () => _section == LobbySection.Settings);
            RegisterNavHover(RoadmapSectionButton, RoadmapSectionIcon, RoadmapSectionTitle, RoadmapSectionSubtitle, () => _section == LobbySection.Roadmap);
            RegisterNavHover(SiteButton, SiteButtonIcon, SiteButtonTitle, SiteButtonSubtitle, () => false);
            RegisterNavHover(LeaveButton, LeaveButtonIcon, LeaveButtonTitle, LeaveButtonSubtitle, () => false);

            _news =
            [
                new EclipseNewsEntry(
                    NewsDate1.Text ?? string.Empty,
                    NewsTitle1.Text ?? string.Empty,
                    NewsText1.Text ?? string.Empty,
                    "/Textures/Eclipse/MainMenu/news/news-tech.png"),
                new EclipseNewsEntry(
                    NewsDate2.Text ?? string.Empty,
                    NewsTitle2.Text ?? string.Empty,
                    NewsText2.Text ?? string.Empty,
                    "/Textures/Eclipse/MainMenu/news/news-update.png"),
                new EclipseNewsEntry(
                    NewsDate3.Text ?? string.Empty,
                    NewsTitle3.Text ?? string.Empty,
                    NewsText3.Text ?? string.Empty,
                    "/Textures/Eclipse/MainMenu/news/news-event.png"),
            ];

            _storeItems =
            [
                new StoreItem("КОСТЮМ ECLIPSE", "Уникальный костюм", "Косметика • Одежда", 600, StoreCurrency.Shards, "/Textures/Clothing/OuterClothing/Hardsuits/deathsquad.rsi/icon.png", "РЕКОМЕНДУЕМОЕ"),
                new StoreItem("ФОРМА КАПИТАНА", "Парадный образ", "Косметика • Одежда", 1500, StoreCurrency.Merits, "/Textures/Clothing/Uniforms/Jumpsuit/captain.rsi/icon.png", "НОВОЕ"),
                new StoreItem("РАМКА «ОРБИТА»", "Профильная рамка", "Косметика • Профиль", 750, StoreCurrency.Merits, "/Textures/Eclipse/MainMenu/news/news-update.png", "НОВОЕ"),
                new StoreItem("ЧАСЫ ЗАТМЕНИЯ", "Лобби-украшение", "Косметика • Лобби", 250, StoreCurrency.Shards, "/Textures/Interface/VerbIcons/clock.svg.192dpi.png", "РЕДКОЕ"),
                new StoreItem("ФОРМА СБ «ЗАТМЕНИЕ»", "Тёмный вариант", "Косметика • Одежда", 900, StoreCurrency.Shards, "/Textures/Clothing/OuterClothing/WinterCoats/coathosarmored.rsi/icon.png", "НОВОЕ"),
                new StoreItem("ФОН ПРОФИЛЯ", "Туманность", "Косметика • Профиль", 350, StoreCurrency.Shards, "/Textures/Eclipse/MainMenu/news/news-event.png", null),
                new StoreItem("ДЕКОР «ФИКУС»", "Уют для лобби", "Косметика • Лобби", 350, StoreCurrency.Merits, "/Textures/_Orion/Structures/Furniture/potted_plants.rsi/plasma_plant.png", "НОВОЕ"),
                new StoreItem("НАБОР НОВИЧКА", "Базовый набор", "Набор", 1200, StoreCurrency.Merits, "/Textures/Objects/Devices/pda.rsi/pda.png", null),
                new StoreItem("РЮКЗАК ИНЖЕНЕРА", "Косметический скин", "Косметика • Спина", 450, StoreCurrency.Merits, "/Textures/_Orion/Clothing/Back/Backpacks/inteq_backpack.rsi/icon.png", "НОВОЕ"),
                new StoreItem("ID-КАРТА 3K", "Облик карты", "Косметика • Аксессуар", 300, StoreCurrency.Merits, "/Textures/_Backmen/Objects/Misc/id_cards.rsi/idstationengineer.png", "НОВОЕ"),
                new StoreItem("ПОСТЕР «ЗАТМЕНИЕ»", "Декор для лобби", "Косметика • Лобби", 300, StoreCurrency.Merits, "/Textures/_Orion/Structures/Wallmounts/Posters/inteq_posters.rsi/inteq_poster1.png", "НОВОЕ"),
                new StoreItem("ДРОН «СМОТРИТЕЛЬ»", "Спутник профиля", "Косметика • Спутник", 600, StoreCurrency.Merits, "/Textures/Eclipse/VA11_HallA/sparklestar.rsi/icon.png", "НОВОЕ"),
            ];

            _roadmapEntries =
            [
                new RoadmapEntry(
                    "Магазин",
                    "Новые витрины, наборы косметики и редкие предметы.",
                    "Скоро",
                    "Июнь 2026",
                    "/Textures/Interface/VerbIcons/outfit.svg.192dpi.png"),
                new RoadmapEntry(
                    "Профиль игрока",
                    "Расширенная страница аккаунта с аватаром, статистикой и прогрессом.",
                    "В разработке",
                    null,
                    "/Textures/Interface/VerbIcons/group.svg.192dpi.png"),
                new RoadmapEntry(
                    "Ранги и награды",
                    "Система заслуг, ранги службы и уникальные награды.",
                    "Планируется",
                    "Август 2026",
                    "/Textures/Interface/examine-star.png"),
                new RoadmapEntry(
                    "Новые режимы и ивенты",
                    "Сезонные события, особые миссии и развитие контента станции.",
                    "Долгосрочно",
                    null,
                    "/Textures/Interface/VerbIcons/clock.svg.192dpi.png"),
            ];

            ApplyLobbyChatStyle();
            BuildStoreCatalog();
            BuildRoadmap();
            SetLaunchStatusVisible(true);
            ShowSection(LobbySection.Play);
            ApplyEclipseLayout();
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            UpdateVotesTab(_voteManager.CanCallVote);
            _voteManager.CanCallVoteChanged += UpdateVotesTab;
        }

        protected override void ExitedTree()
        {
            _voteManager.CanCallVoteChanged -= UpdateVotesTab;

            if (_voteCallMenu is { IsOpen: true })
                _voteCallMenu.Close();

            base.ExitedTree();
        }

        public void SetLaunchStatusVisible(bool visible)
        {
            _launchStatusTargetVisible = visible;

            if (visible)
            {
                LaunchStatus.Visible = true;
                LaunchStatus.ReservesSpace = true;
                LaunchDivider.Visible = true;
                LaunchDivider.ReservesSpace = true;
            }
        }

        public void SetAccountInfo(string accountName, string roleName, int level, int currentExperience, int nextLevelExperience, int merits, int shards)
        {
            AccountName.Text = accountName;
            AccountTitle.Text = roleName;
            AccountRole.Text = EclipseProgression.GetRankName(level);
            AccountLevel.Text = $"Уровень {level}";
            AccountExperience.Text = $"{FormatAmount(currentExperience)} / {FormatAmount(nextLevelExperience)} XP";
            AccountExperienceProgress.Value = nextLevelExperience <= 0
                ? 0f
                : Math.Clamp((float) currentExperience / nextLevelExperience, 0f, 1f);
            MeritBalance.Text = FormatAmount(merits);
            ShardBalance.Text = FormatAmount(shards);
            StoreMeritBalance.Text = FormatAmount(merits);
            StoreShardBalance.Text = FormatAmount(shards);
        }

        private static string FormatAmount(int value)
        {
            return value.ToString("N0", CultureInfo.InvariantCulture).Replace(",", " ");
        }

        public void SetNewsAdminControlsVisible(bool visible)
        {
            NewsAdminButton.Visible = visible;
        }

        private void OpenNewsAdminWindow()
        {
            if (_newsWindow is { Disposed: false, IsOpen: true })
            {
                _newsWindow.MoveToFront();
                return;
            }

            _newsWindow = new EclipseNewsAdminWindow(_news, ApplyNews);
            _newsWindow.OpenCentered();
        }

        private void ApplyNews()
        {
            ApplyNewsItem(_news[0], NewsDate1, NewsTitle1, NewsText1, NewsImage1);
            ApplyNewsItem(_news[1], NewsDate2, NewsTitle2, NewsText2, NewsImage2);
            ApplyNewsItem(_news[2], NewsDate3, NewsTitle3, NewsText3, NewsImage3);
        }

        private static void ApplyNewsItem(EclipseNewsEntry news, Label date, Label title, Label text, TextureRect image)
        {
            date.Text = news.Date;
            title.Text = news.Title;
            text.Text = news.Text;

            if (!string.IsNullOrWhiteSpace(news.TexturePath))
                image.TexturePath = news.TexturePath;
        }

        private void ApplyLobbyChatStyle()
        {
            Chat.ApplyEclipseChatStyle();
        }

        private void BuildStoreCatalog()
        {
            StoreCatalogGrid.RemoveAllChildren();

            for (var i = 1; i < _storeItems.Length; i++)
            {
                StoreCatalogGrid.AddChild(BuildStoreCard(_storeItems[i]));
            }

            if (_storeItems.Length > 0)
                ApplyStoreFeatured(_storeItems[0]);
        }

        private void ApplyStoreFeatured(StoreItem item)
        {
            StoreFeaturedImage.TexturePath = item.TexturePath;
            StoreFeaturedCurrencyIcon.TexturePath = GetStoreCurrencyIcon(item.Currency);
            StoreFeaturedName.Text = item.Name;
            StoreFeaturedDescription.Text = item.Description;
            StoreFeaturedPrice.Text = FormatAmount(item.Price);
        }

        private Control BuildStoreCard(StoreItem item)
        {
            var card = new PanelContainer
            {
                MinSize = new Vector2(204f, 244f),
                SetSize = new Vector2(204f, 244f),
                PanelOverride = StorePanel("#070300F4", item.Currency == StoreCurrency.Shards ? "#7B2BB990" : "#A85E1290", 1, 9, 9),
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 5,
                HorizontalExpand = true,
                VerticalExpand = true,
            };
            card.AddChild(root);

            var imageWrap = new PanelContainer
            {
                MinSize = new Vector2(0f, 92f),
                HorizontalExpand = true,
                PanelOverride = StorePanel("#070300D8", "#A85E1238", 1, 4, 4),
            };
            imageWrap.AddChild(new TextureRect
            {
                TexturePath = item.TexturePath,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalExpand = true,
                VerticalExpand = true,
            });
            root.AddChild(imageWrap);

            if (!string.IsNullOrWhiteSpace(item.Badge))
            {
                root.AddChild(new Label
                {
                    Text = item.Badge,
                    StyleIdentifier = MainMenuControl.StyleIdentifierGoldSmall,
                    ClipText = true,
                });
            }

            root.AddChild(new Label
            {
                Text = item.Name,
                StyleIdentifier = MainMenuControl.StyleIdentifierText,
                ClipText = true,
            });
            root.AddChild(new Label
            {
                Text = item.Kind,
                StyleIdentifier = MainMenuControl.StyleIdentifierTinySubtle,
                ClipText = true,
            });

            var priceRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 5,
                HorizontalExpand = true,
            };
            priceRow.AddChild(new TextureRect
            {
                TexturePath = GetStoreCurrencyIcon(item.Currency),
                SetSize = item.Currency == StoreCurrency.Shards
                    ? new Vector2(20f, 20f)
                    : new Vector2(18f, 18f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
            });
            priceRow.AddChild(new Label
            {
                Text = FormatAmount(item.Price),
                StyleIdentifier = MainMenuControl.StyleIdentifierGoldSmall,
                ClipText = true,
            });
            root.AddChild(priceRow);

            root.AddChild(new Control
            {
                VerticalExpand = true,
            });

            root.AddChild(new Button
            {
                Text = "Купить",
                MinHeight = 30,
                HorizontalExpand = true,
                StyleIdentifier = item.Currency == StoreCurrency.Shards
                    ? MainMenuControl.StyleIdentifierPrimary
                    : MainMenuControl.StyleIdentifierSecondary,
            });

            return card;
        }

        private void BuildRoadmap()
        {
            RoadmapEntries.RemoveAllChildren();
            RoadmapProgressDots.RemoveAllChildren();
            RoadmapProgressDots.Columns = Math.Max(1, _roadmapEntries.Length);

            for (var i = 0; i < _roadmapEntries.Length; i++)
            {
                RoadmapProgressDots.AddChild(BuildRoadmapDot(i == 0));
                RoadmapEntries.AddChild(BuildRoadmapEntry(_roadmapEntries[i], i + 1));
            }
        }

        private static Control BuildRoadmapDot(bool active)
        {
            var wrapper = new BoxContainer
            {
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
            };

            wrapper.AddChild(new Label
            {
                Text = active ? "●" : "○",
                StyleIdentifier = active
                    ? MainMenuControl.StyleIdentifierRoadmapDotActive
                    : MainMenuControl.StyleIdentifierRoadmapDot,
                Align = Label.AlignMode.Center,
            });

            return wrapper;
        }

        private static Control BuildRoadmapEntry(RoadmapEntry entry, int number)
        {
            var card = new PanelContainer
            {
                HorizontalExpand = true,
                MinSize = new Vector2(0f, 112f),
                PanelOverride = StorePanel("#070300D8", "#A85E1280", 1, 24, 18),
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalExpand = true,
                SeparationOverride = 24,
            };
            card.AddChild(root);

            root.AddChild(new Label
            {
                Text = number.ToString("00", CultureInfo.InvariantCulture),
                StyleIdentifier = MainMenuControl.StyleIdentifierRoadmapNumber,
                SetWidth = 70,
                VAlign = Label.VAlignMode.Center,
                Align = Label.AlignMode.Center,
            });

            root.AddChild(new PanelContainer
            {
                SetWidth = 1,
                VerticalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#A85E123F"),
                },
            });

            var iconWrap = new PanelContainer
            {
                SetSize = new Vector2(82f, 82f),
                PanelOverride = StorePanel("#070300A0", "#A85E12A8", 1, 14, 14),
            };
            iconWrap.AddChild(new TextureRect
            {
                TexturePath = entry.IconTexturePath,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                ModulateSelfOverride = Color.FromHex("#E6A11A"),
                HorizontalExpand = true,
                VerticalExpand = true,
            });
            root.AddChild(iconWrap);

            var textColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
                SeparationOverride = 8,
            };
            root.AddChild(textColumn);

            textColumn.AddChild(new Label
            {
                Text = entry.Title,
                StyleIdentifier = MainMenuControl.StyleIdentifierRoadmapItemTitle,
                ClipText = true,
            });
            textColumn.AddChild(new Label
            {
                Text = entry.Description,
                StyleIdentifier = MainMenuControl.StyleIdentifierSubtle,
                ClipText = true,
            });

            root.AddChild(BuildRoadmapBadge(entry));

            return card;
        }

        private static Control BuildRoadmapBadge(RoadmapEntry entry)
        {
            var badge = new PanelContainer
            {
                MinSize = new Vector2(178f, 48f),
                VerticalAlignment = VAlignment.Center,
                PanelOverride = StorePanel("#070300E8", "#F0A51390", 1, 12, 8),
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SeparationOverride = 9,
            };
            badge.AddChild(row);

            row.AddChild(new Label
            {
                Text = entry.Date is null ? "⚙" : "▣",
                StyleIdentifier = MainMenuControl.StyleIdentifierGoldSmall,
                VAlign = Label.VAlignMode.Center,
            });
            row.AddChild(new Label
            {
                Text = entry.Date ?? entry.Status,
                StyleIdentifier = MainMenuControl.StyleIdentifierGoldSmall,
                VAlign = Label.VAlignMode.Center,
                ClipText = true,
            });

            return badge;
        }

        private static string GetStoreCurrencyIcon(StoreCurrency currency)
        {
            return currency == StoreCurrency.Shards
                ? "/Textures/Eclipse/MainMenu/shard.png"
                : "/Textures/Eclipse/MainMenu/merit.png";
        }

        private static EclipseStyleBoxRounded StorePanel(string background, string border, int borderThickness, int horizontalMargin, int verticalMargin)
        {
            var style = new EclipseStyleBoxRounded
            {
                BackgroundColor = Color.FromHex(background),
                BorderColor = Color.FromHex(border),
                BorderThickness = new Thickness(borderThickness),
                Radius = 8f,
            };

            style.SetContentMarginOverride(StyleBox.Margin.Horizontal, horizontalMargin);
            style.SetContentMarginOverride(StyleBox.Margin.Vertical, verticalMargin);
            return style;
        }

        private static void RegisterNavHover(
            Button button,
            TextureRect icon,
            Label title,
            Label subtitle,
            Func<bool> isActive)
        {
            button.OnMouseEntered += _ => SetNavButtonVisual(icon, title, subtitle, true);
            button.OnMouseExited += _ => SetNavButtonVisual(icon, title, subtitle, isActive());
        }

        private static void SetNavButtonVisual(TextureRect icon, Label title, Label subtitle, bool highlighted)
        {
            icon.ModulateSelfOverride = highlighted ? NavActiveColor : NavNormalColor;
            title.ModulateSelfOverride = highlighted ? NavActiveColor : null;
            subtitle.ModulateSelfOverride = highlighted ? NavSubtitleActiveColor : null;
        }

        private void OpenCrewManifest()
        {
            SetRightTabActive(RightSideTab.Manifest);
            _entityManager.System<CrewManifestSystem>().RequestCrewManifest(GetCrewManifestStation());
        }

        private void OpenVoteMenu()
        {
            if (!_voteManager.CanCallVote)
                return;

            if (_voteCallMenu is { IsOpen: true })
            {
                _voteCallMenu.Close();
                return;
            }

            _voteCallMenu = new VoteCallMenu();
            _voteCallMenu.OpenCentered();
        }

        private void UpdateVotesTab(bool canCall)
        {
            VotesTabButton.Disabled = !canCall;
        }

        private NetEntity GetCrewManifestStation()
        {
            var gameTicker = _entityManager.System<ClientGameTicker>();

            foreach (var station in gameTicker.StationNames.Keys)
            {
                if (station.Valid)
                    return station;
            }

            foreach (var station in gameTicker.JobsAvailable.Keys)
            {
                if (station.Valid)
                    return station;
            }

            return NetEntity.Invalid;
        }

        private void SetRightTabActive(RightSideTab tab)
        {
            LobbyTabButton.StyleIdentifier = tab == RightSideTab.Lobby
                ? MainMenuControl.StyleIdentifierTabButtonActive
                : MainMenuControl.StyleIdentifierTabButton;
            ManifestTabButton.StyleIdentifier = tab == RightSideTab.Manifest
                ? MainMenuControl.StyleIdentifierTabButtonActive
                : MainMenuControl.StyleIdentifierTabButton;
            AdminsTabButton.StyleIdentifier = tab == RightSideTab.Admins
                ? MainMenuControl.StyleIdentifierTabButtonActive
                : MainMenuControl.StyleIdentifierTabButton;

            LobbyTabLabel.StyleIdentifier = tab == RightSideTab.Lobby
                ? MainMenuControl.StyleIdentifierTabActive
                : MainMenuControl.StyleIdentifierTab;
            ManifestTabLabel.StyleIdentifier = tab == RightSideTab.Manifest
                ? MainMenuControl.StyleIdentifierTabActive
                : MainMenuControl.StyleIdentifierTab;
            AdminsTabLabel.StyleIdentifier = tab == RightSideTab.Admins
                ? MainMenuControl.StyleIdentifierTabActive
                : MainMenuControl.StyleIdentifierTab;
        }

        private void ShowSection(LobbySection section)
        {
            _section = section;
            var play = section == LobbySection.Play;

            TopStatusPanel.Visible = play;
            NewsPanel.Visible = play;
            ServerActions.Visible = true;
            RightSide.Visible = true;
            BottomActions.Visible = true;
            VoteContainer.Visible = play;
            SectionPanel.Visible = !play;
            SectionHeader.Visible = section != LobbySection.Roadmap;
            SectionDivider.Visible = section != LobbySection.Roadmap;
            StoreContent.Visible = false;
            StoreEmptyContent.Visible = section == LobbySection.Store;
            RoadmapContent.Visible = section == LobbySection.Roadmap;
            StoreHeaderBalances.Visible = false;
            SectionBody.Visible = section != LobbySection.Store && section != LobbySection.Roadmap;
            SectionFiller.Visible = section != LobbySection.Store && section != LobbySection.Roadmap;

            PlaySectionButton.StyleIdentifier = play ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierNav;
            StoreSectionButton.StyleIdentifier = section == LobbySection.Store ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierNav;
            AccountSectionButton.StyleIdentifier = section == LobbySection.Account ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierNav;
            SettingsSectionButton.StyleIdentifier = section == LobbySection.Settings ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierNav;
            RoadmapSectionButton.StyleIdentifier = section == LobbySection.Roadmap ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierNav;
            SetNavButtonVisual(PlaySectionIcon, PlaySectionTitle, PlaySectionSubtitle, play);
            SetNavButtonVisual(StoreSectionIcon, StoreSectionTitle, StoreSectionSubtitle, section == LobbySection.Store);
            SetNavButtonVisual(AccountSectionIcon, AccountSectionTitle, AccountSectionSubtitle, section == LobbySection.Account);
            SetNavButtonVisual(SettingsSectionIcon, SettingsSectionTitle, SettingsSectionSubtitle, section == LobbySection.Settings);
            SetNavButtonVisual(RoadmapSectionIcon, RoadmapSectionTitle, RoadmapSectionSubtitle, section == LobbySection.Roadmap);
            SetNavButtonVisual(SiteButtonIcon, SiteButtonTitle, SiteButtonSubtitle, false);
            SetNavButtonVisual(LeaveButtonIcon, LeaveButtonTitle, LeaveButtonSubtitle, false);

            SectionOptionsButton.Visible = section == LobbySection.Settings;

            switch (section)
            {
                case LobbySection.Play:
                    break;
                case LobbySection.Store:
                    SectionIconTexture.TexturePath = "/Textures/Eclipse/MainMenu/icons/nav-store.png";
                    SectionTitle.Text = "МАГАЗИН";
                    SectionSubtitle.Text = "Витрина нарядов и предметов";
                    break;
                case LobbySection.Account:
                    SectionIconTexture.TexturePath = "/Textures/Eclipse/MainMenu/icons/nav-account.png";
                    SectionTitle.Text = "АККАУНТ";
                    SectionSubtitle.Text = "Профиль, аватар и достижения";
                    SectionBody.Text = "Здесь будет отдельный полноэкранный профиль аккаунта. Аватар можно будет менять в этом разделе.";
                    break;
                case LobbySection.Settings:
                    SectionIconTexture.TexturePath = "/Textures/Interface/VerbIcons/settings.svg.192dpi.png";
                    SectionTitle.Text = "НАСТРОЙКИ";
                    SectionSubtitle.Text = "Игра и интерфейс";
                    SectionBody.Text = "Здесь будет отдельный полноэкранный раздел настроек.";
                    break;
                case LobbySection.Roadmap:
                    SectionIconTexture.TexturePath = "/Textures/Eclipse/MainMenu/icons/nav-roadmap.png";
                    SectionTitle.Text = "ДОРОЖНАЯ КАРТА";
                    SectionSubtitle.Text = "Чего ожидать в будущих обновлениях";
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(section), section, null);
            }

            ApplyEclipseLayout();
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    ShowSection(_section);
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    SectionPanel.Visible = false;
                    TopStatusPanel.Visible = false;
                    NewsPanel.Visible = false;
                    ServerActions.Visible = true;
                    RightSide.Visible = true;
                    BottomActions.Visible = true;
                    VoteContainer.Visible = false;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }

            ApplyEclipseLayout();
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            UpdateLaunchStatusAnimation(args.DeltaSeconds);
            ApplyEclipseLayout();
        }

        private void UpdateLaunchStatusAnimation(float deltaSeconds)
        {
            var target = _launchStatusTargetVisible ? 1f : 0f;
            _launchStatusVisibility = Math.Clamp(
                _launchStatusVisibility + MathF.Sign(target - _launchStatusVisibility) * deltaSeconds * LaunchStatusAnimationSpeed,
                0f,
                1f);

            if (MathF.Abs(_launchStatusVisibility - target) < 0.001f)
                _launchStatusVisibility = target;

            LaunchStatus.Visible = true;
            LaunchStatus.ReservesSpace = true;
            LaunchDivider.Visible = true;
            LaunchDivider.ReservesSpace = true;
            LaunchStatus.SetWidth = LaunchStatusWidth;
            LaunchStatus.Modulate = Color.White.WithAlpha(_launchStatusVisibility);
            LaunchDivider.Modulate = Color.White.WithAlpha(_launchStatusVisibility);
        }

        private void ApplyEclipseLayout()
        {
            var width = MathF.Max(MainContainer.Width, 1f);
            var height = MathF.Max(MainContainer.Height, 1f);
            var rightGap = width < NarrowBreakpoint ? NarrowEdgeGap : EdgeGap;
            var rightWidth = Math.Clamp(width - rightGap - CenterLeft, 320f, RightWidth);
            var rightStart = width - rightGap - rightWidth;
            var availableCenterWidth = rightStart - CenterLeft - 42f;
            var accountWidth = Math.Clamp(availableCenterWidth, 640f, AccountWidthWithLaunch);
            var newsWidth = Math.Min(NewsWidth, Math.Max(availableCenterWidth, 320f));

            SetLeftStretch(LeftSide, 0f, SidebarWidth);
            SetTopLeft(TopStatusPanel, CenterLeft, TopGap, accountWidth, AccountHeight);
            SetBottomLeft(NewsPanel, CenterLeft, NewsBottomGap, newsWidth, NewsHeight);
            SetTopRight(ServerActions, rightGap, TopGap, rightWidth, ServerActionsHeight);
            SetRightStretch(RightSide, rightGap, RightPanelTop, rightWidth, RightPanelBottomGap);
            SetTopRight(ExpandPanel, rightGap, RightPanelTop, 44f, 44f);
            SetBottomRight(BottomActions, rightGap, BottomGap, rightWidth, BottomActionsHeight);
            SetTopLeft(VoteContainer, CenterLeft, TopGap + AccountHeight + 12f, Math.Clamp(accountWidth, 360f, 640f), 180f);
            var centerRightReserve = RightSide.Visible ? rightGap + rightWidth + 28f : rightGap;
            SetTopLeft(SectionPanel, SidebarWidth, 0f, MathF.Max(width - SidebarWidth - centerRightReserve, 1f), height);

            var setupLeft = SidebarWidth + 28f;
            var setupWidth = Math.Max(width - setupLeft - centerRightReserve, 480f);
            SetTopLeft(CharacterSetupState, setupLeft, TopGap, setupWidth, MathF.Max(height - TopGap - BottomGap, 640f));
        }

        private static void SetTopLeft(Control control, float left, float top, float width, float height)
        {
            LayoutContainer.SetAnchorLeft(control, 0f);
            LayoutContainer.SetAnchorTop(control, 0f);
            LayoutContainer.SetAnchorRight(control, 0f);
            LayoutContainer.SetAnchorBottom(control, 0f);
            LayoutContainer.SetMarginLeft(control, left);
            LayoutContainer.SetMarginTop(control, top);
            LayoutContainer.SetMarginRight(control, left + width);
            LayoutContainer.SetMarginBottom(control, top + height);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetTopRight(Control control, float right, float top, float width, float height)
        {
            LayoutContainer.SetAnchorLeft(control, 1f);
            LayoutContainer.SetAnchorTop(control, 0f);
            LayoutContainer.SetAnchorRight(control, 1f);
            LayoutContainer.SetAnchorBottom(control, 0f);
            LayoutContainer.SetMarginLeft(control, -(right + width));
            LayoutContainer.SetMarginTop(control, top);
            LayoutContainer.SetMarginRight(control, -right);
            LayoutContainer.SetMarginBottom(control, top + height);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetBottomLeft(Control control, float left, float bottom, float width, float height)
        {
            LayoutContainer.SetAnchorLeft(control, 0f);
            LayoutContainer.SetAnchorTop(control, 1f);
            LayoutContainer.SetAnchorRight(control, 0f);
            LayoutContainer.SetAnchorBottom(control, 1f);
            LayoutContainer.SetMarginLeft(control, left);
            LayoutContainer.SetMarginTop(control, -(bottom + height));
            LayoutContainer.SetMarginRight(control, left + width);
            LayoutContainer.SetMarginBottom(control, -bottom);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetBottomRight(Control control, float right, float bottom, float width, float height)
        {
            LayoutContainer.SetAnchorLeft(control, 1f);
            LayoutContainer.SetAnchorTop(control, 1f);
            LayoutContainer.SetAnchorRight(control, 1f);
            LayoutContainer.SetAnchorBottom(control, 1f);
            LayoutContainer.SetMarginLeft(control, -(right + width));
            LayoutContainer.SetMarginTop(control, -(bottom + height));
            LayoutContainer.SetMarginRight(control, -right);
            LayoutContainer.SetMarginBottom(control, -bottom);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetRightStretch(Control control, float right, float top, float width, float bottom)
        {
            LayoutContainer.SetAnchorLeft(control, 1f);
            LayoutContainer.SetAnchorTop(control, 0f);
            LayoutContainer.SetAnchorRight(control, 1f);
            LayoutContainer.SetAnchorBottom(control, 1f);
            LayoutContainer.SetMarginLeft(control, -(right + width));
            LayoutContainer.SetMarginTop(control, top);
            LayoutContainer.SetMarginRight(control, -right);
            LayoutContainer.SetMarginBottom(control, -bottom);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        private static void SetLeftStretch(Control control, float left, float width)
        {
            LayoutContainer.SetAnchorLeft(control, 0f);
            LayoutContainer.SetAnchorTop(control, 0f);
            LayoutContainer.SetAnchorRight(control, 0f);
            LayoutContainer.SetAnchorBottom(control, 1f);
            LayoutContainer.SetMarginLeft(control, left);
            LayoutContainer.SetMarginTop(control, 0f);
            LayoutContainer.SetMarginRight(control, left + width);
            LayoutContainer.SetMarginBottom(control, 0f);
            LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }

        private enum LobbySection : byte
        {
            Play,
            Store,
            Account,
            Settings,
            Roadmap,
        }

        private enum RightSideTab : byte
        {
            Lobby,
            Manifest,
            Admins,
        }

        private enum StoreCurrency : byte
        {
            Merits,
            Shards,
        }

        private sealed record StoreItem(
            string Name,
            string Description,
            string Kind,
            int Price,
            StoreCurrency Currency,
            string TexturePath,
            string? Badge);

        private sealed record RoadmapEntry(
            string Title,
            string Description,
            string Status,
            string? Date,
            string IconTexturePath);

        private sealed class EclipseNewsEntry
        {
            public EclipseNewsEntry(string date, string title, string text, string texturePath)
            {
                Date = date;
                Title = title;
                Text = text;
                TexturePath = texturePath;
            }

            public string Date { get; set; }
            public string Title { get; set; }
            public string Text { get; set; }
            public string TexturePath { get; set; }
        }

        private sealed class EclipseNewsAdminWindow : DefaultWindow
        {
            private readonly EclipseNewsEntry[] _entries;
            private readonly Action _onSaved;
            private readonly LineEdit[] _dateEdits = new LineEdit[3];
            private readonly LineEdit[] _titleEdits = new LineEdit[3];
            private readonly LineEdit[] _textEdits = new LineEdit[3];
            private readonly LineEdit[] _textureEdits = new LineEdit[3];

            public EclipseNewsAdminWindow(EclipseNewsEntry[] entries, Action onSaved)
            {
                _entries = entries;
                _onSaved = onSaved;

                Title = "Eclipse news";
                MinSize = new Vector2(620f, 500f);

                var root = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = 10,
                    Margin = new Thickness(12),
                    HorizontalExpand = true,
                    VerticalExpand = true,
                };

                for (var i = 0; i < entries.Length; i++)
                {
                    root.AddChild(BuildEditor(i));
                }

                var saveButton = new Button
                {
                    Text = "Save news",
                    MinHeight = 36,
                    HorizontalExpand = true,
                };
                saveButton.OnPressed += _ => SaveAndClose();
                root.AddChild(saveButton);

                Contents.AddChild(root);
            }

            private Control BuildEditor(int index)
            {
                var entry = _entries[index];
                var box = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = 4,
                    HorizontalExpand = true,
                };

                box.AddChild(new Label
                {
                    Text = $"News {index + 1}",
                    StyleIdentifier = MainMenuControl.StyleIdentifierGoldSmall,
                });

                _dateEdits[index] = AddLineEdit(box, "Date", entry.Date);
                _titleEdits[index] = AddLineEdit(box, "Title", entry.Title);
                _textEdits[index] = AddLineEdit(box, "Text", entry.Text);
                _textureEdits[index] = AddLineEdit(box, "Texture path", entry.TexturePath);

                return box;
            }

            private static LineEdit AddLineEdit(BoxContainer parent, string placeholder, string text)
            {
                var edit = new LineEdit
                {
                    PlaceHolder = placeholder,
                    Text = text,
                    HorizontalExpand = true,
                };
                parent.AddChild(edit);
                return edit;
            }

            private void SaveAndClose()
            {
                for (var i = 0; i < _entries.Length; i++)
                {
                    _entries[i].Date = _dateEdits[i].Text.Trim();
                    _entries[i].Title = _titleEdits[i].Text.Trim();
                    _entries[i].Text = _textEdits[i].Text.Trim();
                    _entries[i].TexturePath = _textureEdits[i].Text.Trim();
                }

                _onSaved();
                Close();
            }
        }
    }
}
