using Content.Shared._Erida.Botany.SeedDna;
using Content.Shared.Atmos;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Erida.Botany.UI;

[GenerateTypedNameReferences]
public sealed partial class SeedDnaConsoleWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly List<SeedDnaConsoleWindowRow> _allRows = [];
    private readonly SeedDnaConsoleBoundUserInterface _owner;

    private bool _flagUpdateImmediately = true;
    private bool _seedIsPresent;
    private bool _dnaDiskIsPresent;
    private SeedDataDto? _seedDataDto;
    private SeedDataDto? _dnaDiskDataDto;

    public SeedDnaConsoleWindow(SeedDnaConsoleBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _owner = owner;

        ExtractAllButton.OnPressed += _ =>
        {
            _flagUpdateImmediately = false;
            foreach (var row in _allRows)
            {
                row.DoExtract();
            }

            ExtractAllButton.Disabled = true;
            ReplaceAllButton.Disabled = true;
            SubmitUpdateDto(TargetSeedData.DnaDisk);
            _flagUpdateImmediately = true;
        };

        ReplaceAllButton.OnPressed += _ =>
        {
            _flagUpdateImmediately = false;
            foreach (var row in _allRows)
            {
                row.DoReplace();
            }

            ExtractAllButton.Disabled = true;
            ReplaceAllButton.Disabled = true;
            SubmitUpdateDto(TargetSeedData.Seed);
            _flagUpdateImmediately = true;
        };
    }

    public void UpdateState(SeedDnaConsoleBoundUserInterfaceState state)
    {
        UpdateEjectButtons(state);

        if (!ValidateSeed(state))
            return;

        SetupDataDto(state);
        CleanRows();
        FillRows();
        UpdateButtonsAll(state);
    }

    private void UpdateEjectButtons(SeedDnaConsoleBoundUserInterfaceState state)
    {
        _seedIsPresent = state.IsSeedsPresent;
        _dnaDiskIsPresent = state.IsDnaDiskPresent;

        SeedButton.Text = state.IsSeedsPresent
            ? Loc.GetString("seed-dna-eject-btn")
            : Loc.GetString("seed-dna-insert-btn");
        SeedLabel.Text = state.SeedsName;

        DnaDiskButton.Text = state.IsDnaDiskPresent
            ? Loc.GetString("seed-dna-eject-btn")
            : Loc.GetString("seed-dna-insert-btn");
        DnaDiskLabel.Text = state.DnaDiskName;
    }

    private bool ValidateSeed(SeedDnaConsoleBoundUserInterfaceState state)
    {
        if (state is { IsSeedsPresent: true, SeedData: null })
        {
            InvalidSeedLabel.Visible = true;
            MutationContainer.Visible = false;
            ExtractAllButton.Disabled = true;
            ReplaceAllButton.Disabled = true;
            return false;
        }

        InvalidSeedLabel.Visible = false;
        MutationContainer.Visible = true;
        return true;
    }

    private void SetupDataDto(SeedDnaConsoleBoundUserInterfaceState state)
    {
        _seedDataDto = state.SeedData;
        _dnaDiskDataDto = state.DnaDiskData ?? new SeedDataDto();
    }

    private void CleanRows()
    {
        MutationContainer.Children.Clear();
        ExtractAllButton.Disabled = true;
        ReplaceAllButton.Disabled = true;
        _allRows.Clear();
    }

    private void FillRows()
    {
        if (!_seedIsPresent && !_dnaDiskIsPresent)
            return;

        var getSeedPotency = new Func<float?>(() => _seedDataDto?.Potency);
        var getDiskPotency = new Func<float?>(() => _dnaDiskDataDto?.Potency ?? (_seedIsPresent ? _seedDataDto?.Potency : null));

        FillChemicalRows(getSeedPotency, getDiskPotency);
        FillGasRows();

        AppendFloatRow(Loc.GetString("seed-dna-row-NutrientConsumption"), () => _seedDataDto?.NutrientConsumption, value => _seedDataDto!.NutrientConsumption = value, () => _dnaDiskDataDto?.NutrientConsumption, value => _dnaDiskDataDto!.NutrientConsumption = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-WaterConsumption"), () => _seedDataDto?.WaterConsumption, value => _seedDataDto!.WaterConsumption = value, () => _dnaDiskDataDto?.WaterConsumption, value => _dnaDiskDataDto!.WaterConsumption = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-IdealHeat"), () => _seedDataDto?.IdealHeat, value => _seedDataDto!.IdealHeat = value, () => _dnaDiskDataDto?.IdealHeat, value => _dnaDiskDataDto!.IdealHeat = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-HeatTolerance"), () => _seedDataDto?.HeatTolerance, value => _seedDataDto!.HeatTolerance = value, () => _dnaDiskDataDto?.HeatTolerance, value => _dnaDiskDataDto!.HeatTolerance = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-IdealLight"), () => _seedDataDto?.IdealLight, value => _seedDataDto!.IdealLight = value, () => _dnaDiskDataDto?.IdealLight, value => _dnaDiskDataDto!.IdealLight = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-LightTolerance"), () => _seedDataDto?.LightTolerance, value => _seedDataDto!.LightTolerance = value, () => _dnaDiskDataDto?.LightTolerance, value => _dnaDiskDataDto!.LightTolerance = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-ToxinsTolerance"), () => _seedDataDto?.ToxinsTolerance, value => _seedDataDto!.ToxinsTolerance = value, () => _dnaDiskDataDto?.ToxinsTolerance, value => _dnaDiskDataDto!.ToxinsTolerance = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-LowPressureTolerance"), () => _seedDataDto?.LowPressureTolerance, value => _seedDataDto!.LowPressureTolerance = value, () => _dnaDiskDataDto?.LowPressureTolerance, value => _dnaDiskDataDto!.LowPressureTolerance = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-HighPressureTolerance"), () => _seedDataDto?.HighPressureTolerance, value => _seedDataDto!.HighPressureTolerance = value, () => _dnaDiskDataDto?.HighPressureTolerance, value => _dnaDiskDataDto!.HighPressureTolerance = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-PestTolerance"), () => _seedDataDto?.PestTolerance, value => _seedDataDto!.PestTolerance = value, () => _dnaDiskDataDto?.PestTolerance, value => _dnaDiskDataDto!.PestTolerance = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-WeedTolerance"), () => _seedDataDto?.WeedTolerance, value => _seedDataDto!.WeedTolerance = value, () => _dnaDiskDataDto?.WeedTolerance, value => _dnaDiskDataDto!.WeedTolerance = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-WeedHighLevelThreshold"), () => _seedDataDto?.WeedHighLevelThreshold, value => _seedDataDto!.WeedHighLevelThreshold = value, () => _dnaDiskDataDto?.WeedHighLevelThreshold, value => _dnaDiskDataDto!.WeedHighLevelThreshold = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-Endurance"), () => _seedDataDto?.Endurance, value => _seedDataDto!.Endurance = value, () => _dnaDiskDataDto?.Endurance, value => _dnaDiskDataDto!.Endurance = value);
        AppendIntRow(Loc.GetString("seed-dna-row-Yield"), () => _seedDataDto?.Yield, value => _seedDataDto!.Yield = value, () => _dnaDiskDataDto?.Yield, value => _dnaDiskDataDto!.Yield = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-Lifespan"), () => _seedDataDto?.Lifespan, value => _seedDataDto!.Lifespan = value, () => _dnaDiskDataDto?.Lifespan, value => _dnaDiskDataDto!.Lifespan = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-Maturation"), () => _seedDataDto?.Maturation, value => _seedDataDto!.Maturation = value, () => _dnaDiskDataDto?.Maturation, value => _dnaDiskDataDto!.Maturation = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-Production"), () => _seedDataDto?.Production, value => _seedDataDto!.Production = value, () => _dnaDiskDataDto?.Production, value => _dnaDiskDataDto!.Production = value);
        AppendEnumRow(Loc.GetString("seed-dna-row-HarvestRepeat"), () => _seedDataDto?.HarvestRepeat, value => _seedDataDto!.HarvestRepeat = value, () => _dnaDiskDataDto?.HarvestRepeat, value => _dnaDiskDataDto!.HarvestRepeat = value);
        AppendFloatRow(Loc.GetString("seed-dna-row-Potency"), () => _seedDataDto?.Potency, value => _seedDataDto!.Potency = value, () => _dnaDiskDataDto?.Potency, value => _dnaDiskDataDto!.Potency = value);
        AppendBoolRow(Loc.GetString("seed-dna-row-Seedless"), () => _seedDataDto?.Seedless, value => _seedDataDto!.Seedless = value, () => _dnaDiskDataDto?.Seedless, value => _dnaDiskDataDto!.Seedless = value);
        AppendBoolRow(Loc.GetString("seed-dna-row-Viable"), () => _seedDataDto?.Viable, value => _seedDataDto!.Viable = value, () => _dnaDiskDataDto?.Viable, value => _dnaDiskDataDto!.Viable = value);
        AppendBoolRow(Loc.GetString("seed-dna-row-Ligneous"), () => _seedDataDto?.Ligneous, value => _seedDataDto!.Ligneous = value, () => _dnaDiskDataDto?.Ligneous, value => _dnaDiskDataDto!.Ligneous = value);
        AppendBoolRow(Loc.GetString("seed-dna-row-CanScream"), () => _seedDataDto?.CanScream, value => _seedDataDto!.CanScream = value, () => _dnaDiskDataDto?.CanScream, value => _dnaDiskDataDto!.CanScream = value);
        AppendBoolRow(Loc.GetString("seed-dna-row-TurnIntoKudzu"), () => _seedDataDto?.TurnIntoKudzu, value => _seedDataDto!.TurnIntoKudzu = value, () => _dnaDiskDataDto?.TurnIntoKudzu, value => _dnaDiskDataDto!.TurnIntoKudzu = value);
    }

    private void FillChemicalRows(Func<float?> getSeedPotency, Func<float?> getDiskPotency)
    {
        if (_seedDataDto?.Chemicals?.Count <= 0 && _dnaDiskDataDto?.Chemicals?.Count <= 0)
            return;

        var processed = new HashSet<string>();

        if (_seedDataDto?.Chemicals != null)
        {
            foreach (var (chemicalName, _) in _seedDataDto.Chemicals)
            {
                processed.Add(chemicalName);
                AppendChemicalRow(chemicalName, getSeedPotency, getDiskPotency);
            }
        }

        if (_dnaDiskDataDto?.Chemicals == null)
            return;

        foreach (var (chemicalName, _) in _dnaDiskDataDto.Chemicals)
        {
            if (!processed.Add(chemicalName))
                continue;

            AppendChemicalRow(chemicalName, getSeedPotency, getDiskPotency);
        }
    }

    private void AppendChemicalRow(string chemicalName, Func<float?> getSeedPotency, Func<float?> getDiskPotency)
    {
        AppendRow(SeedDnaConsoleWindowRow.Create(
            title: GetChemicalName(chemicalName),
            seedPresent: _seedIsPresent,
            dnaDiskPresent: _dnaDiskIsPresent,
            getterSeedValue: () =>
            {
                if (_seedDataDto?.Chemicals != null && _seedDataDto.Chemicals.TryGetValue(chemicalName, out var value))
                    return value;
                return null;
            },
            setterSeedValue: obj =>
            {
                _seedDataDto!.Chemicals ??= new Dictionary<string, SeedChemQuantityDto>();
                _seedDataDto.Chemicals[chemicalName] = (SeedChemQuantityDto) obj!;
            },
            getterDnaDiskValue: () =>
            {
                if (_dnaDiskDataDto?.Chemicals != null && _dnaDiskDataDto.Chemicals.TryGetValue(chemicalName, out var value))
                    return value;
                return null;
            },
            setterDnaDiskValue: obj =>
            {
                _dnaDiskDataDto!.Chemicals ??= new Dictionary<string, SeedChemQuantityDto>();
                _dnaDiskDataDto.Chemicals[chemicalName] = (SeedChemQuantityDto) obj!;
            },
            getSeedPotency: getSeedPotency,
            getDiskPotency: getDiskPotency,
            flagUpdateImmediately: () => _flagUpdateImmediately,
            submit: SubmitUpdateDto,
            refreshRows: RefreshRows
        ));
    }

    private void FillGasRows()
    {
        if (_seedDataDto?.ConsumeGasses?.Count > 0 || _dnaDiskDataDto?.ConsumeGasses?.Count > 0)
        {
            foreach (var gas in Enum.GetValues<Gas>())
            {
                AppendFloatRow(
                    Loc.GetString("seed-dna-row-consume-gas", ("gas", GetGasName(gas))),
                    () => GetGasValue(_seedDataDto?.ConsumeGasses, gas),
                    value => SetGasValue(_seedDataDto!, gas, value, true),
                    () => GetGasValue(_dnaDiskDataDto?.ConsumeGasses, gas),
                    value => SetGasValue(_dnaDiskDataDto!, gas, value, true));
            }
        }

        if (_seedDataDto?.ExudeGasses?.Count > 0 || _dnaDiskDataDto?.ExudeGasses?.Count > 0)
        {
            foreach (var gas in Enum.GetValues<Gas>())
            {
                AppendFloatRow(
                    Loc.GetString("seed-dna-row-exude-gas", ("gas", GetGasName(gas))),
                    () => GetGasValue(_seedDataDto?.ExudeGasses, gas),
                    value => SetGasValue(_seedDataDto!, gas, value, false),
                    () => GetGasValue(_dnaDiskDataDto?.ExudeGasses, gas),
                    value => SetGasValue(_dnaDiskDataDto!, gas, value, false));
            }
        }
    }

    private void AppendFloatRow(string title, Func<float?> getterSeedValue, Action<float> setterSeedValue, Func<float?> getterDnaDiskValue, Action<float> setterDnaDiskValue)
    {
        AppendRow(SeedDnaConsoleWindowRow.Create(
            title,
            _seedIsPresent,
            _dnaDiskIsPresent,
            getterSeedValue: () => getterSeedValue(),
            getterDnaDiskValue: () => getterDnaDiskValue(),
            setterSeedValue: obj => setterSeedValue((float) obj!),
            setterDnaDiskValue: obj => setterDnaDiskValue((float) obj!),
            flagUpdateImmediately: () => _flagUpdateImmediately,
            submit: SubmitUpdateDto,
            refreshRows: RefreshRows
        ));
    }

    private void AppendIntRow(string title, Func<int?> getterSeedValue, Action<int> setterSeedValue, Func<int?> getterDnaDiskValue, Action<int> setterDnaDiskValue)
    {
        AppendRow(SeedDnaConsoleWindowRow.Create(
            title,
            _seedIsPresent,
            _dnaDiskIsPresent,
            getterSeedValue: () => getterSeedValue(),
            getterDnaDiskValue: () => getterDnaDiskValue(),
            setterSeedValue: obj => setterSeedValue((int) obj!),
            setterDnaDiskValue: obj => setterDnaDiskValue((int) obj!),
            flagUpdateImmediately: () => _flagUpdateImmediately,
            submit: SubmitUpdateDto,
            refreshRows: RefreshRows
        ));
    }

    private void AppendBoolRow(string title, Func<bool?> getterSeedValue, Action<bool> setterSeedValue, Func<bool?> getterDnaDiskValue, Action<bool> setterDnaDiskValue)
    {
        AppendRow(SeedDnaConsoleWindowRow.Create(
            title,
            _seedIsPresent,
            _dnaDiskIsPresent,
            getterSeedValue: () => getterSeedValue(),
            getterDnaDiskValue: () => getterDnaDiskValue(),
            setterSeedValue: obj => setterSeedValue((bool) obj!),
            setterDnaDiskValue: obj => setterDnaDiskValue((bool) obj!),
            flagUpdateImmediately: () => _flagUpdateImmediately,
            submit: SubmitUpdateDto,
            refreshRows: RefreshRows
        ));
    }

    private void AppendEnumRow(string title, Func<SharedHarvestTypeDto?> getterSeedValue, Action<SharedHarvestTypeDto> setterSeedValue, Func<SharedHarvestTypeDto?> getterDnaDiskValue, Action<SharedHarvestTypeDto> setterDnaDiskValue)
    {
        AppendRow(SeedDnaConsoleWindowRow.Create(
            title,
            _seedIsPresent,
            _dnaDiskIsPresent,
            getterSeedValue: () => getterSeedValue(),
            getterDnaDiskValue: () => getterDnaDiskValue(),
            setterSeedValue: obj => setterSeedValue((SharedHarvestTypeDto) obj!),
            setterDnaDiskValue: obj => setterDnaDiskValue((SharedHarvestTypeDto) obj!),
            flagUpdateImmediately: () => _flagUpdateImmediately,
            submit: SubmitUpdateDto,
            refreshRows: RefreshRows
        ));
    }

    private void UpdateButtonsAll(SeedDnaConsoleBoundUserInterfaceState state)
    {
        if (state is not { IsSeedsPresent: true, IsDnaDiskPresent: true })
            return;

        if (state.SeedData != null)
            ExtractAllButton.Disabled = false;

        if (state.DnaDiskData != null)
            ReplaceAllButton.Disabled = false;
    }

    private void SubmitUpdateDto(TargetSeedData target)
    {
        _owner.SubmitData(target, target == TargetSeedData.Seed ? _seedDataDto! : _dnaDiskDataDto!);
    }

    private void RefreshRows()
    {
        foreach (var row in _allRows)
        {
            row.RefreshValues();
        }
    }

    private void AppendRow(SeedDnaConsoleWindowRow? row)
    {
        if (row == null)
            return;

        row.IncludeToContainer(MutationContainer);
        _allRows.Add(row);
    }

    private static float? GetGasValue(Dictionary<Gas, float>? data, Gas gas)
    {
        return data != null && data.TryGetValue(gas, out var value) ? value : null;
    }

    private static void SetGasValue(SeedDataDto dto, Gas gas, float value, bool consume)
    {
        if (consume)
        {
            dto.ConsumeGasses ??= new Dictionary<Gas, float>();
            dto.ConsumeGasses[gas] = value;
            return;
        }

        dto.ExudeGasses ??= new Dictionary<Gas, float>();
        dto.ExudeGasses[gas] = value;
    }

    private string GetChemicalName(string chemicalName)
    {
        if (_prototypeManager.TryIndex<ReagentPrototype>(chemicalName, out var reagent))
            return reagent.LocalizedName;

        if (_localizationManager.TryGetString($"seed-dna-chemical-{chemicalName}", out var localized))
            return localized;

        return chemicalName;
    }

    private string GetGasName(Gas gas)
    {
        var key = gas switch
        {
            Gas.Oxygen => "gas-oxygen",
            Gas.Nitrogen => "gas-nitrogen",
            Gas.CarbonDioxide => "gas-carbon-dioxide",
            Gas.Plasma => "gas-plasma",
            Gas.Tritium => "gas-tritium",
            Gas.WaterVapor => "gas-water-vapor",
            Gas.Ammonia => "gas-ammonia",
            Gas.NitrousOxide => "gas-nitrous-oxide",
            Gas.Frezon => "gas-frezon",
            _ => null
        };

        return key != null && _localizationManager.TryGetString(key, out var localized)
            ? localized
            : gas.ToString();
    }
}
