using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class TraitPreferenceSelector : Control
{
    public int Cost;
    private string? _description;

    public bool Preference
    {
        get => Checkbox.Pressed;
        set => Checkbox.Pressed = value;
    }

    public bool Disabled
    {
        get => Checkbox.Disabled;
        set => Checkbox.Disabled = value;
    }

    public event Action<bool>? PreferenceChanged;

    public TraitPreferenceSelector(TraitPrototype trait, int? displayCost = null)
    {
        RobustXamlLoader.Load(this);

        var cost = displayCost ?? trait.Cost;
        var text = Loc.GetString(trait.Name);
        text += $" [{cost:+#;-#;0}]";

        Cost = trait.Cost;
        Checkbox.Text = text;
        Checkbox.OnToggled += OnCheckBoxToggled;

        if (trait.Description is { } desc)
        {
            _description = Loc.GetString(desc);
            Checkbox.ToolTip = _description;
        }
    }

    public void SetBlockReason(string? reason)
    {
        Disabled = reason != null;
        Checkbox.Label.FontColorOverride = reason != null ? Color.Gray : null;
        Checkbox.ToolTip = reason == null
            ? _description
            : _description == null
                ? reason
                : $"{_description}\n{reason}";
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        PreferenceChanged?.Invoke(Preference);
    }
}
