using System.Linq;
using System.Text;
using Content.Client.Actions;
using Content.Client.GameTicking.Managers;
using Content.Client.Message;
using Content.Shared.Armor;
using Content.Shared.Clothing;
using Content.Shared.Containers;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.FixedPoint;
using Content.Shared.Item.ItemToggle.Components;
using Content.Shared.Projectiles;
using Content.Shared.Storage.Components;
using Content.Shared.Store;
using Content.Shared.Weapons.Melee;
using Content.Shared.Weapons.Ranged.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Store.Ui;

[GenerateTypedNameReferences]
public sealed partial class StoreMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private StoreWithdrawWindow? _withdrawWindow;
    private ClientGameTicker _ticker = default!;

    public event EventHandler<string>? SearchTextUpdated;
    public event Action<BaseButton.ButtonEventArgs, ListingDataWithCostModifiers>? OnListingButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string>? OnCategoryButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string, int>? OnWithdrawAttempt;
    public event Action<BaseButton.ButtonEventArgs>? OnRefundAttempt;

    public Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> Balance = new();
    public string CurrentCategory = string.Empty;

    private List<ListingDataWithCostModifiers> _cachedListings = new();
    private readonly List<StoreListingControl> _listingControls = new();
    private ListingDataWithCostModifiers? _selectedListing;
    private Texture? _selectedTexture;
    private string _selectedPrice = string.Empty;
    private string _selectedDiscount = string.Empty;
    private bool _selectedHasBalance;
    private StoreUiTheme _theme = StoreUiTheme.Legion;

    public StoreMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _ticker = _entityManager.System<ClientGameTicker>();

        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
        RefundButton.OnButtonDown += OnRefundButtonDown;
        PurchaseButton.OnButtonDown += OnPurchaseButtonDown;
        SearchBar.OnTextChanged += _ => SearchTextUpdated?.Invoke(this, SearchBar.Text);

        SortOptionButton.AddItem(Loc.GetString("store-ui-sort-default"));
        SortOptionButton.SelectId(0);
        FilterOptionButton.AddItem(Loc.GetString("store-ui-filter-all"));
        FilterOptionButton.SelectId(0);

        UpdateSelectedPanel();
    }

    public void SetTheme(StoreUiTheme theme)
    {
        if (_theme == theme)
            return;

        _theme = theme;

        switch (_theme)
        {
            case StoreUiTheme.Spellbook:
                Title = Loc.GetString("store-ui-spellbook-title");
                HeaderTitle.Text = Loc.GetString("store-ui-spellbook-title-caps");
                HeaderSubtitle.Text = Loc.GetString("store-ui-spellbook-subtitle");
                HeaderIcon.TexturePath = "/Textures/Objects/Magic/magicactions.rsi/spell_default.png";
                StatsPanel.Visible = false;
                break;

            default:
                Title = Loc.GetString("store-ui-legion-terminal-title");
                HeaderTitle.Text = Loc.GetString("store-ui-legion-terminal-title-caps");
                HeaderSubtitle.Text = Loc.GetString("store-ui-legion-terminal-subtitle");
                HeaderIcon.TexturePath = "/Textures/Interface/Actions/shop.png";
                StatsPanel.Visible = true;
                break;
        }

        UpdateSelectedPanel();
    }

    public void UpdateBalance(Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> balance)
    {
        Balance = balance;

        var currency = balance.ToDictionary(type =>
            (type.Key, type.Value), type => _prototypeManager.Index(type.Key));

        var balanceStr = string.Empty;
        foreach (var ((_, amount), proto) in currency)
        {
            balanceStr += Loc.GetString("store-ui-balance-display", ("amount", amount),
                ("currency", Loc.GetString(proto.DisplayName, ("amount", 1)))) + "\n";
        }

        BalanceInfo.SetMarkup(balanceStr.TrimEnd());

        var disabled = true;
        foreach (var type in currency)
        {
            if (type.Value.CanWithdraw && type.Value.Cash != null && type.Key.Item2 > 0)
            {
                disabled = false;
                break;
            }
        }

        WithdrawButton.Disabled = disabled;
    }

    public void UpdateListing(List<ListingDataWithCostModifiers> listings)
    {
        _cachedListings = listings;

        UpdateListing();
    }

    public void UpdateListing()
    {
        var sorted = _cachedListings.OrderBy(l => l.Priority)
                                    .ThenBy(l => l.Cost.Values.Sum())
                                    .ToList();

        var firstVisible = sorted.FirstOrDefault(l => l.Categories.Contains(CurrentCategory));
        var selectedVisible = _selectedListing != null
            && sorted.Any(l => l.ID == _selectedListing.ID && l.Categories.Contains(CurrentCategory));
        if (!selectedVisible)
            _selectedListing = firstVisible;

        // should probably chunk these out instead. to-do if this clogs the internet tubes.
        // maybe read clients prototypes instead?
        ClearListings();
        foreach (var item in sorted)
        {
            AddListingGui(item);
        }

        UpdateSelectedPanel();
        UpdateListingSelection();
    }

    public void SetFooterVisibility(bool visible)
    {
        TraitorFooter.Visible = visible;
    }

    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        // check if window is already open
        if (_withdrawWindow != null && _withdrawWindow.IsOpen)
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        // open a new one
        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();

        _withdrawWindow.CreateCurrencyButtons(Balance);
        _withdrawWindow.OnWithdrawAttempt += OnWithdrawAttempt;
    }

    private void OnRefundButtonDown(BaseButton.ButtonEventArgs args)
    {
        OnRefundAttempt?.Invoke(args);
    }

    private void OnPurchaseButtonDown(BaseButton.ButtonEventArgs args)
    {
        if (_selectedListing == null || !CanBuy(_selectedListing, _selectedHasBalance))
            return;

        OnListingButtonPressed?.Invoke(args, _selectedListing);
    }

    private void AddListingGui(ListingDataWithCostModifiers listing)
    {
        if (!listing.Categories.Contains(CurrentCategory))
            return;

        var hasBalance = listing.CanBuyWith(Balance);

        var spriteSys = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();

        Texture? texture = null;
        if (listing.Icon != null)
            texture = spriteSys.Frame0(listing.Icon);

        if (listing.ProductEntity != null)
        {
            if (texture == null)
                texture = spriteSys.GetPrototypeIcon(listing.ProductEntity).Default;
        }
        else if (listing.ProductAction != null)
        {
            var actionId = _entityManager.Spawn(listing.ProductAction);
            if (_entityManager.System<ActionsSystem>().GetAction(actionId)?.Comp?.Icon is {} icon)
                texture = spriteSys.Frame0(icon);
        }

        var listingInStock = GetListingPriceString(listing);
        var discount = GetDiscountString(listing);

        var newListing = new StoreListingControl(listing, listingInStock, discount, texture);
        newListing.Selected += () =>
            SelectListing(listing, texture, listingInStock, discount, hasBalance);

        _listingControls.Add(newListing);
        StoreListingsContainer.AddChild(newListing);

        if (_selectedListing?.ID == listing.ID)
        {
            _selectedTexture = texture;
            _selectedPrice = listingInStock;
            _selectedDiscount = discount;
            _selectedHasBalance = hasBalance;
        }
    }

    private void SelectListing(
        ListingDataWithCostModifiers listing,
        Texture? texture,
        string price,
        string discount,
        bool hasBalance)
    {
        _selectedListing = listing;
        _selectedTexture = texture;
        _selectedPrice = price;
        _selectedDiscount = discount;
        _selectedHasBalance = hasBalance;

        UpdateSelectedPanel();
        UpdateListingSelection();
    }

    private string GetListingPriceString(ListingDataWithCostModifiers listing)
    {
        var text = string.Empty;

        if (listing.Cost.Count < 1)
            text = Loc.GetString("store-currency-free");
        else
        {
            foreach (var (type, amount) in listing.Cost)
            {
                var currency = _prototypeManager.Index(type);

                text += Loc.GetString(
                    "store-ui-price-display",
                    ("amount", amount),
                    ("currency", Loc.GetString(currency.DisplayName, ("amount", amount)))
                );
            }
        }

        return text.TrimEnd();
    }

    private string GetDiscountString(ListingDataWithCostModifiers listingDataWithCostModifiers)
    {
        string discountMessage;

        if (!listingDataWithCostModifiers.IsCostModified)
        {
            return string.Empty;
        }

        var relativeModifiersSummary = listingDataWithCostModifiers.GetModifiersSummaryRelative();
        if (relativeModifiersSummary.Count > 1)
        {
            var sb = new StringBuilder();
            sb.Append('(');
            foreach (var (currency, amount) in relativeModifiersSummary)
            {
                var currencyPrototype = _prototypeManager.Index(currency);
                if (sb.Length != 0)
                {
                    sb.Append(", ");
                }
                var currentDiscountMessage = Loc.GetString(
                    "store-ui-discount-display-with-currency",
                    ("amount", amount.ToString("P0")),
                    ("currency", Loc.GetString(currencyPrototype.DisplayName))
                );
                sb.Append(currentDiscountMessage);
            }

            sb.Append(')');
            discountMessage = sb.ToString();
        }
        else
        {
            // if cost was modified - it should have diff relatively to original cost in 1 or more currency
            // ReSharper disable once GenericEnumeratorNotDisposed Dictionary enumerator doesn't require dispose
            var enumerator = relativeModifiersSummary.GetEnumerator();
            enumerator.MoveNext();
            var amount = enumerator.Current.Value;
            discountMessage = Loc.GetString(
                "store-ui-discount-display",
                ("amount", (amount.ToString("P0")))
            );
        }

        return discountMessage;
    }

    private void ClearListings()
    {
        StoreListingsContainer.Children.Clear();
        _listingControls.Clear();
    }

    public void PopulateStoreCategoryButtons(HashSet<ListingDataWithCostModifiers> listings)
    {
        var allCategories = new List<StoreCategoryPrototype>();
        foreach (var listing in listings)
        {
            foreach (var cat in listing.Categories)
            {
                var proto = _prototypeManager.Index(cat);
                if (!allCategories.Contains(proto))
                    allCategories.Add(proto);
            }
        }

        allCategories = allCategories.OrderBy(c => c.Priority).ToList();

        // This will reset the Current Category selection if nothing matches the search.
        if (allCategories.All(category => category.ID != CurrentCategory))
            CurrentCategory = string.Empty;

        if (CurrentCategory == string.Empty && allCategories.Count > 0)
            CurrentCategory = allCategories.First().ID;

        CategoryListContainer.Children.Clear();
        if (allCategories.Count < 1)
            return;

        var group = new ButtonGroup();
        foreach (var proto in allCategories)
        {
            var catButton = new StoreCategoryButton
            {
                Text = Loc.GetString(proto.Name),
                Id = proto.ID,
                Pressed = proto.ID == CurrentCategory,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "OpenBoth" }
            };

            catButton.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, catButton.Id);
            CategoryListContainer.AddChild(catButton);
        }
    }

    private void UpdateSelectedPanel()
    {
        if (_selectedListing == null)
        {
            SelectedItemName.SetMarkup(GetSelectedNameMarkup(Loc.GetString("store-ui-no-selection")));
            SelectedItemSubtitle.Text = string.Empty;
            SelectedItemDescription.SetMarkup(string.Empty);
            SelectedItemTexture.Texture = null;
            SelectedFooterTexture.Texture = null;
            SelectedFooterName.Text = Loc.GetString("store-ui-no-selection");
            SelectedFooterPrice.Text = string.Empty;
            SelectedPriceLabel.Text = "-";
            SelectedAvailabilityLabel.Text = "-";
            SelectedDiscountLabel.Text = string.Empty;
            SetWeaponStats(null);
            PurchaseButton.Text = Loc.GetString("store-ui-buy-button-empty");
            PurchaseButton.Disabled = true;
            return;
        }

        var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_selectedListing, _prototypeManager);
        var description = ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_selectedListing, _prototypeManager);

        SelectedItemName.SetMarkup(GetSelectedNameMarkup(name));
        SelectedItemSubtitle.Text = Loc.GetString(_theme == StoreUiTheme.Spellbook
            ? "store-ui-selected-spell-subtitle"
            : "store-ui-selected-subtitle");
        SelectedItemDescription.SetMessage(description);
        SelectedItemTexture.Texture = _selectedTexture;
        SelectedFooterTexture.Texture = _selectedTexture;
        SelectedFooterName.Text = name;
        SelectedFooterPrice.Text = _selectedPrice;
        SelectedPriceLabel.Text = _selectedPrice;
        SelectedDiscountLabel.Text = _selectedDiscount;
        SetWeaponStats(GetWeaponStats(_selectedListing));

        UpdateSelectedPurchaseState();
    }

    private void SetWeaponStats(WeaponStats? stats)
    {
        switch (stats?.Type)
        {
            case WeaponStatsType.Melee:
                SetStatNames(
                    "store-ui-stat-damage",
                    "store-ui-stat-dps",
                    "store-ui-stat-structural",
                    "store-ui-stat-attack-rate",
                    "store-ui-stat-melee-range");

                SetStat(DamageStatBar, DamageStatValue, stats?.Damage, 100);
                SetStat(DpsStatBar, DpsStatValue, stats?.Dps, 200);
                SetStat(AccuracyStatBar, AccuracyStatValue, stats?.Accuracy, 100);
                SetStat(FireRateStatBar, FireRateStatValue, stats?.FireRate, 5);
                SetStat(MagazineStatBar, MagazineStatValue, stats?.MagazineCapacity, 3);
                break;

            case WeaponStatsType.Armor:
                SetStatNames(
                    "store-ui-stat-armor-blunt",
                    "store-ui-stat-armor-slash",
                    "store-ui-stat-armor-piercing",
                    "store-ui-stat-armor-heat",
                    "store-ui-stat-speed");

                SetStat(DamageStatBar, DamageStatValue, stats?.Damage, 100, "%");
                SetStat(DpsStatBar, DpsStatValue, stats?.Dps, 100, "%");
                SetStat(AccuracyStatBar, AccuracyStatValue, stats?.Accuracy, 100, "%");
                SetStat(FireRateStatBar, FireRateStatValue, stats?.FireRate, 100, "%");
                SetStat(MagazineStatBar, MagazineStatValue, stats?.MagazineCapacity, 100, "%");
                break;

            default:
                SetStatNames(
                    "store-ui-stat-damage",
                    "store-ui-stat-dps",
                    "store-ui-stat-accuracy",
                    "store-ui-stat-fire-rate",
                    "store-ui-stat-magazine");

                SetStat(DamageStatBar, DamageStatValue, stats?.Damage, 80);
                SetStat(DpsStatBar, DpsStatValue, stats?.Dps, 160);
                SetStat(AccuracyStatBar, AccuracyStatValue, stats?.Accuracy, 100);
                SetStat(FireRateStatBar, FireRateStatValue, stats?.FireRate, 10);
                SetStat(MagazineStatBar, MagazineStatValue, stats?.MagazineCapacity, 50);
                break;
        }
    }

    private void SetStatNames(string first, string second, string third, string fourth, string fifth)
    {
        DamageStatName.Text = Loc.GetString(first);
        DpsStatName.Text = Loc.GetString(second);
        AccuracyStatName.Text = Loc.GetString(third);
        FireRateStatName.Text = Loc.GetString(fourth);
        MagazineStatName.Text = Loc.GetString(fifth);
    }

    private static void SetStat(ProgressBar bar, Label label, float? value, float max, string suffix = "")
    {
        if (value == null)
        {
            bar.Value = 0;
            label.Text = "-";
            return;
        }

        bar.Value = Math.Clamp(value.Value / max * 100f, 0f, 100f);
        var formatted = value.Value % 1 == 0
            ? value.Value.ToString("0")
            : value.Value.ToString("0.0");
        label.Text = $"{formatted}{suffix}";
    }

    private static string GetSelectedNameMarkup(string name)
    {
        return $"[bold][color=#F2F2F2]{FormattedMessage.EscapeText(name)}[/color][/bold]";
    }

    private WeaponStats? GetWeaponStats(ListingDataWithCostModifiers listing)
    {
        if (listing.ProductEntity == null ||
            !_prototypeManager.TryIndex<EntityPrototype>(listing.ProductEntity.Value, out var entity))
            return null;

        var statsEntity = ResolveStatsEntity(entity);
        var factory = _entityManager.ComponentFactory;
        entity = statsEntity;

        if (entity.TryGetComponent<GunComponent>(out var gun, factory))
        {
            var damage = TryGetGunDamage(entity) ?? 0f;
            var fireRate = gun.FireRate;
            var accuracy = GetAccuracy(entity, gun);
            var capacity = TryGetGunCapacity(entity) ?? 0;

            return new WeaponStats(
                WeaponStatsType.Ranged,
                damage > 0 ? damage : null,
                damage > 0 ? damage * fireRate : null,
                accuracy,
                fireRate,
                capacity > 0 ? capacity : null);
        }

        if (entity.TryGetComponent<MeleeWeaponComponent>(out var melee, factory))
        {
            var damageSpec = melee.Damage;
            if (entity.TryGetComponent<ItemToggleMeleeWeaponComponent>(out var toggleMelee, factory) &&
                toggleMelee.ActivatedDamage != null)
                damageSpec = toggleMelee.ActivatedDamage;

            var damage = GetDamageTotal(damageSpec, false);
            var structuralDamage = GetStructuralDamage(damageSpec);
            return new WeaponStats(
                WeaponStatsType.Melee,
                damage,
                damage * melee.AttackRate,
                structuralDamage > 0 ? structuralDamage : null,
                melee.AttackRate,
                melee.Range);
        }

        if (TryGetArmorStats(entity, out var armorStats))
            return armorStats;

        return null;
    }

    private bool TryGetArmorStats(EntityPrototype entity, out WeaponStats stats)
    {
        var factory = _entityManager.ComponentFactory;
        var hasArmor = entity.TryGetComponent<ArmorComponent>(out var armor, factory);
        var hasSpeed = entity.TryGetComponent<ClothingSpeedModifierComponent>(out var speed, factory);

        stats = new WeaponStats(
            WeaponStatsType.Armor,
            armor?.GetProtection("Blunt"),
            armor?.GetProtection("Slash"),
            armor?.GetProtection("Piercing"),
            armor?.GetProtection("Heat"),
            speed?.SprintModifier * 100f);

        return hasArmor || hasSpeed;
    }

    private EntityPrototype ResolveStatsEntity(EntityPrototype entity)
    {
        var factory = _entityManager.ComponentFactory;
        var visited = new HashSet<EntProtoId>();
        var queue = new Queue<EntityPrototype>();
        queue.Enqueue(entity);

        while (queue.TryDequeue(out var current))
        {
            if (current.TryGetComponent<GunComponent>(out _, factory) ||
                current.TryGetComponent<MeleeWeaponComponent>(out _, factory))
                return current;

            foreach (var contained in GetFilledEntityPrototypes(current))
            {
                if (!visited.Add(contained))
                    continue;

                if (_prototypeManager.TryIndex<EntityPrototype>(contained, out var containedEntity))
                    queue.Enqueue(containedEntity);
            }
        }

        return entity;
    }

    private IEnumerable<EntProtoId> GetFilledEntityPrototypes(EntityPrototype entity)
    {
        var factory = _entityManager.ComponentFactory;

        if (entity.TryGetComponent<StorageFillComponent>(out var storageFill, factory))
        {
            foreach (var entry in storageFill.Contents)
            {
                if (entry.PrototypeId != null)
                    yield return entry.PrototypeId.Value;
            }
        }

        if (entity.TryGetComponent<ContainerFillComponent>(out var containerFill, factory))
        {
            foreach (var container in containerFill.Containers.Values)
            {
                foreach (var prototype in container)
                    yield return prototype;
            }
        }
    }

    private float GetAccuracy(EntityPrototype entity, GunComponent gun)
    {
        var maxAngle = gun.MaxAngle;
        if (entity.TryGetComponent<GunWieldBonusComponent>(out var wieldBonus, _entityManager.ComponentFactory))
            maxAngle += wieldBonus.MaxAngle;

        var degrees = MathF.Max(0f, (float) maxAngle.Degrees);
        return Math.Clamp(100f - degrees * 4f, 0f, 100f);
    }

    private float? TryGetGunDamage(EntityPrototype entity)
    {
        var ammo = TryGetGunAmmoPrototype(entity);
        if (ammo == null)
            return null;

        return TryGetProjectileDamage(ammo.Value);
    }

    private EntProtoId? TryGetGunAmmoPrototype(EntityPrototype entity)
    {
        var factory = _entityManager.ComponentFactory;

        if (entity.TryGetComponent<BallisticAmmoProviderComponent>(out var ballistic, factory))
            return ballistic.Proto;

        if (entity.TryGetComponent<BasicEntityAmmoProviderComponent>(out var basic, factory))
            return basic.Proto;

        if (entity.TryGetComponent<BatteryAmmoProviderComponent>(out var battery, factory))
            return battery.Prototype;

        if (entity.TryGetComponent<RevolverAmmoProviderComponent>(out var revolver, factory))
            return revolver.FillPrototype;

        if (entity.TryGetComponent<ItemSlotsComponent>(out var slots, factory))
        {
            foreach (var slot in slots.Slots.Values)
            {
                if (slot.StartingItem == null ||
                    !_prototypeManager.TryIndex<EntityPrototype>(slot.StartingItem, out var magazine))
                    continue;

                if (magazine.TryGetComponent<BallisticAmmoProviderComponent>(out var magazineAmmo, factory))
                    return magazineAmmo.Proto;
            }
        }

        return null;
    }

    private int? TryGetGunCapacity(EntityPrototype entity)
    {
        var factory = _entityManager.ComponentFactory;

        if (entity.TryGetComponent<BallisticAmmoProviderComponent>(out var ballistic, factory))
            return ballistic.Capacity;

        if (entity.TryGetComponent<BasicEntityAmmoProviderComponent>(out var basic, factory))
            return basic.Capacity;

        if (entity.TryGetComponent<BatteryAmmoProviderComponent>(out var battery, factory))
            return battery.Capacity;

        if (entity.TryGetComponent<RevolverAmmoProviderComponent>(out var revolver, factory))
            return revolver.Capacity;

        if (entity.TryGetComponent<ItemSlotsComponent>(out var slots, factory))
        {
            foreach (var slot in slots.Slots.Values)
            {
                if (slot.StartingItem == null ||
                    !_prototypeManager.TryIndex<EntityPrototype>(slot.StartingItem, out var magazine))
                    continue;

                if (magazine.TryGetComponent<BallisticAmmoProviderComponent>(out var magazineAmmo, factory))
                    return magazineAmmo.Capacity;
            }
        }

        return null;
    }

    private float? TryGetProjectileDamage(EntProtoId ammoPrototype)
    {
        var factory = _entityManager.ComponentFactory;
        if (!_prototypeManager.TryIndex<EntityPrototype>(ammoPrototype, out var ammo))
            return null;

        var projectileId = ammoPrototype;
        if (ammo.TryGetComponent<CartridgeAmmoComponent>(out var cartridge, factory))
            projectileId = cartridge.Prototype;

        if (!_prototypeManager.TryIndex<EntityPrototype>(projectileId, out var projectileProto) ||
            !projectileProto.TryGetComponent<ProjectileComponent>(out var projectile, factory))
            return null;

        return GetDamageTotal(projectile.Damage, true);
    }

    private static float GetDamageTotal(Content.Shared.Damage.DamageSpecifier damage, bool includeStructural)
    {
        var total = 0f;
        foreach (var (type, amount) in damage.DamageDict)
        {
            if (!includeStructural && type.Id == "Structural")
                continue;

            total += amount.Float();
        }

        return total;
    }

    private static float GetStructuralDamage(Content.Shared.Damage.DamageSpecifier damage)
    {
        foreach (var (type, amount) in damage.DamageDict)
        {
            if (type.Id == "Structural")
                return amount.Float();
        }

        return 0f;
    }

    private void UpdateSelectedPurchaseState()
    {
        if (_selectedListing == null)
            return;

        var canBuy = CanBuy(_selectedListing, _selectedHasBalance);
        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_selectedListing.RestockTime > stationTime)
        {
            var timeLeftToBuy = stationTime - _selectedListing.RestockTime;
            SelectedAvailabilityLabel.Text = timeLeftToBuy.Duration().ToString(@"mm\:ss");
        }
        else
        {
            SelectedAvailabilityLabel.Text = Loc.GetString("store-ui-in-stock");
        }

        PurchaseButton.Disabled = !canBuy;
        PurchaseButton.Text = canBuy
            ? Loc.GetString("store-ui-buy-button", ("price", _selectedPrice))
            : Loc.GetString("store-ui-buy-button-unavailable");
    }

    private void UpdateListingSelection()
    {
        foreach (var control in _listingControls)
        {
            control.SetSelected(_selectedListing != null && control.ListingId == _selectedListing.ID);
        }
    }

    private bool CanBuy(ListingDataWithCostModifiers listing, bool hasBalance)
    {
        if (!hasBalance)
            return false;

        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        return listing.RestockTime <= stationTime;
    }

    private enum WeaponStatsType : byte
    {
        Ranged,
        Melee,
        Armor
    }

    private readonly record struct WeaponStats(
        WeaponStatsType Type,
        float? Damage,
        float? Dps,
        float? Accuracy,
        float? FireRate,
        float? MagazineCapacity);

    public override void Close()
    {
        base.Close();
        _withdrawWindow?.Close();
    }

    public void UpdateRefund(bool allowRefund)
    {
        RefundButton.Visible = allowRefund;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSelectedPurchaseState();
    }

    private sealed class StoreCategoryButton : Button
    {
        public string? Id;
    }
}
