using Content.Client.GameTicking.Managers;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Store.Ui;

[GenerateTypedNameReferences]
public sealed partial class StoreListingControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly ClientGameTicker _ticker;

    private readonly ListingDataWithCostModifiers _data;

    private readonly string _price;
    private readonly string _discount;
    private bool _selected;

    public event Action? Selected;
    public string ListingId => _data.ID;

    public StoreListingControl(ListingDataWithCostModifiers data, string price, string discount, Texture? texture = null)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _ticker = _entity.System<ClientGameTicker>();

        _data = data;
        _price = price;
        _discount = discount;
        MouseFilter = MouseFilterMode.Stop;
        DefaultCursorShape = CursorShape.Hand;
        OnKeyBindDown += OnListingKeyBindDown;
        OnMouseEntered += _ => UpdatePanelStyle(true);
        OnMouseExited += _ => UpdatePanelStyle(false);

        StoreItemName.Text = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);
        StoreItemDescription.Text = ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype);
        StoreItemPrice.Text = _price;
        DiscountSubText.Text = _discount;

        UpdateAvailability();

        StoreItemTexture.Texture = texture;
    }

    public void SetSelected(bool selected)
    {
        _selected = selected;
        UpdatePanelStyle(false);
    }

    private void OnListingKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Selected?.Invoke();
        args.Handle();
    }

    private void UpdatePanelStyle(bool hovered)
    {
        var background = _selected ? Color.FromHex("#FF7A00") : hovered ? Color.FromHex("#180D04") : Color.FromHex("#070707");
        var border = _selected ? Color.FromHex("#FF7A00") : Color.FromHex("#1F1F1F");
        StoreItemPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(1)
        };

        StoreItemName.FontColorOverride = _selected ? Color.White : Color.FromHex("#F0F0F0");
        StoreItemDescription.FontColorOverride = _selected ? Color.White : Color.FromHex("#9A9A9A");
        AvailabilityLabel.FontColorOverride = _selected ? Color.White : Color.FromHex("#FF7A00");
        StoreItemPrice.FontColorOverride = _selected ? Color.White : Color.FromHex("#FF7A00");
    }

    private void UpdateAvailability()
    {
        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
        {
            var timeLeftToBuy = stationTime - _data.RestockTime;
            AvailabilityLabel.Text = timeLeftToBuy.Duration().ToString(@"mm\:ss");
        }
        else
        {
            AvailabilityLabel.Text = Loc.GetString("store-ui-in-stock");
        }

        StoreItemPrice.Text = _price;
        DiscountSubText.Text = _discount;
    }

    private void UpdateName()
    {
        var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);

        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
        {
            name += Loc.GetString("store-ui-button-out-of-stock");
        }

        StoreItemName.Text = name;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateAvailability();
        UpdateName();
    }
}
